# SHARK ATTACK DEATH PREVENTION
## Marketing campaign

In [1]:
import pandas as pd

In [2]:
full_file = pd.read_csv('./GSAF5.csv', engine='python')

### This is the full file uploaded from the folder

In [3]:
full_file

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,Fishing,Occupant: Ben Stratton,NaN,...,NaN,"West Australian, 9/15/2016",2016.09.15.R-boat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.15.R,2016.09.15.R,5988,NaN,NaN
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,male,M,...,3' to 4' shark,"News4Jax, 9/11/2016",2016.09.11-PonteVedra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.11,2016.09.11,5987,NaN,NaN
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",Swimming,female,F,...,"Tiger shark, 10?","Hawaii News Now, 9/7/2016",2016.09.07-Oahu.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.07,2016.09.07,5986,NaN,NaN
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,Kite surfing,David Jewell,M,...,NaN,"TVANouvelles, 9/6/2016",2016.09.06-Jewell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.06,2016.09.06,5985,NaN,NaN
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",Boogie boarding,Rylie Williams,F,...,NaN,"C. Creswell, GSAF",2016.09.05.b-Williams.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.b,2016.09.05.b,5984,NaN,NaN
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,Surfing,Fraser Penman,M,...,NaN,"Perth Now, 9/5/2016",2016.09.05.a-Penman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.05.a,2016.09.05.a,5983,NaN,NaN
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Body boarding,Austin Moore,M,...,NaN,"Orlando Sentinel, 9/7/2016",2016.09.04-Moore.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.04,2016.09.04,5982,NaN,NaN
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",Spearfishing,Tyler McQuillen,M,...,White shark,"R. Collier, GSAF",2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.01,2016.09.01,5981,NaN,NaN
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Sam Cumiskey,M,...,"Bull shark, 6'","News Channel 8, 8/30/16",2016.08.29.b-Cumiskey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.b,2016.08.29.b,5980,NaN,NaN
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"News Channel 8, 8/30/16",2016.08.29.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.29.a,2016.08.29.a,5979,NaN,NaN
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,Surfing,Laurent Chardard,M,...,"Bull shark, 3.5 m","LaDepeche, 8/29/2016",2016.08.27-Chardard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.27,2016.08.27,5978,NaN,NaN
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",Wading,David Cassetty,M,...,NaN,"First Coast News, 7/25/2016",2016.08.25-Cassetty.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.25,2016.08.25,5977,NaN,NaN
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,Snorkeling,Johnny Stoch,M,...,NaN,"ABC, 8/11/2016",2016.08.07-Stoch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.07,2016.08.07,5976,NaN,NaN
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,SUP Foil boarding,Connor Baxter,M,...,"Tiger shark, 10'","SUP, 8/9/2015",2016.08.06-Baxter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.06,2016.08.06,5975,NaN,NaN
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Nolan Tyler,M,...,Blacktip shark,"News 965, 8/5/2016",2016.06.04-Tyler.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.08.04,2016.08.04,5974,NaN,NaN
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,...,Blue shark,"Informacion.es, 7/29/2016",2016.07.29-Spain.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.29,2016.07.29,5973,NaN,NaN
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,Swimming,Justus Franz,M,...,NaN,"Klassick, 7/28/2016",2016.07.28.R-Franz.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28.R,2016.07.28.R,5972,NaN,NaN
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,Kayaking,Ian Watkins,M,...,White shark,"ABC Australia, 7/28/2016",2016.07.28-Watkins.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.28,2016.07.28,5971,NaN,NaN
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",Lobstering,Warren Sapp,M,...,"Nurse shark, 4'","Tampa Bay Times, 7/27/2016",2016.07.27-Sapp.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.27,2016.07.27,5970,NaN,NaN
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",Surfing,Curran See & Harry Lake,M,...,NaN,"Gold Coast Bulletin, 7/28/2016",2016.07.26-Ballina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.26,2016.07.26,5969,NaN,NaN
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,Surfing,male,M,...,NaN,"Japan Times, 7/25/2016",2016.07.24-Japan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.24,2016.07.24,5968,NaN,NaN
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,Surfing,Zebulon Critchlow,M,...,NaN,"C. Black, GSAF",2016.07.23.b-Critchlow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.b,2016.07.23.b,5967,NaN,NaN
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,Spearfishing,Steve Cutbirth,M,...,"Bull shark, 6'","KWTX, 7/23/2016",2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.23.a,2016.07.23.a,5966,NaN,NaN
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",Fishing,Scott van Burck,M,...,"reef shark, 1m","Nine News, 7/20/2016",2016.07.20-Burck.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.20,2016.07.20,5965,NaN,NaN
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,Fishing in Alabama Deep Fishing Rodeo,Occupant: Ben Raines,NaN,...,"Tiger shark, 10'","Al.com, 7/19/2016",2016.07.17-Gulf.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.17,2016.07.17,5964,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,"Aircraft ditched in the sea, swimming ashore",male,M,...,NaN,"V.M. Coppleson (1962), p.257",ND-0031-Ditched-Aircrat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0031,ND.0031,31,NaN,NaN
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,Bathing,male,M,...,NaN,"Massillon Independent, 3/1905",ND-0030-Burma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0030,ND.0030,30,NaN,NaN
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,Wooden fishing boat,Occupant: Mr. Maciotta,M,...,White shark,A. De Maddalena; Anon. (1938),ND-0028-Maciotta.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0028,ND.0028,29,NaN,NaN
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,Sponge diving,Psarofa-gomenes,M,...,NaN,M. N. Kalafatas,ND-0027-Psarofagomenos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0027,ND.0027,28,NaN,NaN
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,Standing,a servant,M,...,12' tiger shark,Mitchell-Hedges,ND-0026-Belize.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0026,ND.0026,27,NaN,NaN
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,"Spectacle Island, Port Jackson",NaN,"male, the Sergeant of Marines",M,...,NaN,H. Capper,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0025,ND.0025,26,NaN,NaN
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,Swimming,NaN,NaN,...,NaN,G. Van Grevelynghe,ND-0024-Barachois-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0024,ND.0024,25,NaN,NaN
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,Wading,Madelaine Dalton,F,...,NaN,"L. Green in Tavern of the Seas, p.182",ND-0023-Dalton.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0023,ND.0023,24,NaN,NaN
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,Pearl diving,Jaringoorli,M,...,NaN,"Adelaide Advertiser, 1/11/1940",ND-0022-Jaringoorli.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0022,ND.0022,23,NaN,NaN
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Swimming in pool formed by construction of a w...,Indian boy,M,...,NaN,"L. Green in South African Beachcomber, p.97",ND-0021-DurbanIndianBoy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0021,ND.0021,22,NaN,NaN
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,Great Barrier Reef,NaN,3 Japanese divers,M,...,NaN,"V.M. Coppleson (1958), p.241",ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0020,ND.0020,21,NaN,NaN
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",Fishing,James Kelley,M,...,NaN,"T. Helm, p.219",ND-0019-Kelley.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0019,ND.0019,20,NaN,NaN
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng T�u,Swimming around anchored ship,crewman,M,...,NaN,"Daily Kennebec Journal, 3/27/1911",ND-0018-Vietnam.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0018,ND.0018,19,NaN,NaN
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0017-alongside-ship.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0017,ND.0017,18,NaN,NaN
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,NaN,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0016- Durban-PostOffice.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0016,ND.0016,17,NaN,NaN
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,Wreck of large double sailing canoe,20 Fijians,NaN,...,NaN,"Fijian Society papers presented April 17, 1918...",ND-0015-FijianCanoe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0015,ND.0015,16,NaN,NaN
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,NaN,"C. Creswell, GSAF; Wilmington Star, 7/17/1916",ND-0014-pre1916-NorthCarolina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0014,ND.0014,15,NaN,NaN
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Fishing,a native fisherman,M,...,NaN,"Rural New Yorker, 7/19/1913",ND-0013-Durban-native-fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0013,ND.0013,14,NaN,NaN
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Wading,a young Scotsman,M,...,NaN,"Rural New Yorker, 7/19/1913",ND-0012-Durban-Scotsman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0012,ND.0012,13,NaN,NaN
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,Swimming,Mr. Masury,M,...,NaN,"Ref. J. T. Dubois in N.Y. Sun, 3/19/1911",ND-0011-Masury.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0011,ND.0011,12,NaN,NaN
5982,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,Puna,NaN,A chiefess,F,...,NaN,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11,NaN,NaN
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10,NaN,NaN
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9,NaN,NaN
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,...,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8,NaN,NaN
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,...,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7,NaN,NaN
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6,NaN,NaN
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5,NaN,NaN
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4,NaN,NaN
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8�N, 79�W",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3,NaN,NaN
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2,NaN,NaN

#### After reading all of the files contained in Kaggel, analyzing the full file and some research, I started to think the things I could do with the information I had, and decided that some columns were not going to be usefull in any case, even if the had no null values.

In [4]:
null_cols = full_file.isnull().sum()
null_cols[null_cols > 0]
null_cols

Case Number                  0
Date                         0
Year                         0
Type                         0
Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
pdf                          0
href formula                 1
href                         3
Case Number.1                0
Case Number.2                0
original order               0
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

### So, I decided to delete them with the drop method.

In [5]:
data_clean = full_file.drop(columns=['Investigator or Source', 'pdf', 'href formula', 'href', 'Case Number.1', 'Case Number.2', 'Unnamed: 22', 'Unnamed: 23']).copy()
data_clean.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,5989

#### In order to know all the calculations for the analysis, I needed to know the type of the values contained in the table. Execept the year and the original order, all were strings. That is something I knew I would have to change in the future but decided to do it later on when I had my hypothesis clear.

In [6]:
data_clean.dtypes

Case Number       object
Date              object
Year               int64
Type              object
Country           object
Area              object
Location          object
Activity          object
Name              object
Sex               object
Age               object
Injury            object
Fatal (Y/N)       object
Time              object
Species           object
original order     int64
dtype: object

#### After re-analyzing the data set, I realized that the most complete columns were: type, activity, country, age and sex. So, knowing the information in those columns was "good" I decided to start cleaning those columns in order to get the cleanest data set and decided that my analysis was going to be oriented towards building a segmentation of the type of person attacked by sharks (only for the unprovoked attacks, by country and create segments by activity, sex and age) in order to created advices of what to do and what not to do in beaches and areas with sharks or how to be carefull in any case.

In [7]:
data_clean["Type"].value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: Type, dtype: int64

#### No doubt the messiest column was the one describing the activity the victim was doing at the attack moment. So I started cleaning that column by grouping some common words by activity already mentioned and renaming each one if necessary.

In [8]:
data_clean["Activity"].value_counts()

Surfing                                                                                                                904
Swimming                                                                                                               819
Fishing                                                                                                                414
Spearfishing                                                                                                           321
Bathing                                                                                                                153
Wading                                                                                                                 144
Diving                                                                                                                 123
Standing                                                                                                                97
Snorkeling                                                                                                              77
Scuba diving                                                                                                            74
Body boarding                                                                                                           54
Body surfing                                                                                                            48
Swimming                                                                                                                47
Treading water                                                                                                          32
Pearl diving                                                                                                            32
Kayaking                                                                                                                28
Boogie boarding                                                                                                         28
Free diving                                                                                                             26
Fell overboard                                                                                                          21
Windsurfing                                                                                                             18
Boogie Boarding                                                                                                         16
Walking                                                                                                                 15
Shark fishing                                                                                                           15
Canoeing                                                                                                                12
Fishing                                                                                                                 12
Floating                                                                                                                12
Rowing                                                                                                                  12
Surf skiing                                                                                                             12
Surf-skiing                                                                                                             12
Surf fishing                                                                                                            11
                                                                                                                      ...
Fishing, setting nets                                                                                                    1
Standing, gathering oysters                                                                                              1
Resting on body board                                                                                                    1
Cleaning fish                                                                                                            1
Washed off catamaran in the surf                                                                                         1
Explosion destroyed 28' boat, survivors in the water                                                                     1
Bitten while cutting shark from net                                                                                      1
Lying atop surfboard                                                                                                     1
Fell off surfboard 20' from shore                                                                                        1
Feeling the shark�s teeth                                                                                                1
Riding horseback across the creek                                                                                        1
Attempting to illegally enter the USA                                                                                    1
Murder victim                                                                                                            1
Feeding a shark                                                                                                          1
Longling fishing                                                                                                         1
Floating on an inflatable raft                                                                                           1
Standing, collecting sea stars                                                                                           1
Man fell overboard from ship. Those on board threw a rope to him with a wooden block & were pulling him to the ship      1
Air Disaster - Piper aircraft crashed into the sea, killing all on board                                                 1
Fishing for pompano                                                                                                      1
Diving, retrieving film package from Titan 3C rocket                                                                     1
Wind surfing                                                                                                             1
Cleaning the side of a ship                                                                                              1
Boarding a ship                                                                                                          1
Coming ashore on a hawser                                                                                                1
Dragging banana seeds through the shallows                                                                               1
Shark Fishing                                                                                                            1
Diving (Helmet) for sponges                                                                                              1
Spearfishing using scuba                                                                                                 1
Floating or standing                                                                                                     1
Name: Activity, Length: 1492, dtype: int64

#### So I started defining functions for each of the activities and grouping by common words in the description. I defined A LOT of functions, because I didn't have very clear how to do it with the lambda funtion.

#### First was grouping all the fishing activities in a same activity called "Fishng and other types"

In [9]:
def traducefish(m):
    a=str(m).lower()
    for word in ["fish", "fishing", "clamming", "lobstering", "crabbing", "hunting lobsters"]:
        if word in a:
            return "fishing and other types"
    return a

In [10]:
data_clean['Activity'] = data_clean['Activity'].apply(traducefish)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                                                     1195
surfing                                                                                                                                                                                                                                      904
swimming                                                                                                                                                                                                                                     819
nan                                                                                                                                                                                                                                          527
bathing                                                                                                                                                                                                                                      153
wading                                                                                                                                                                                                                                       144
diving                                                                                                                                                                                                                                       123
standing                                                                                                                                                                                                                                      97
scuba diving                                                                                                                                                                                                                                  81
snorkeling                                                                                                                                                                                                                                    77
body boarding                                                                                                                                                                                                                                 57
body surfing                                                                                                                                                                                                                                  48
swimming                                                                                                                                                                                                                                      47
boogie boarding                                                                                                                                                                                                                               44
treading water                                                                                                                                                                                                                                32
pearl diving                                                                                                                                                                                                                                  32
kayaking                                                                                                                                                                                                                                      28
free diving                                                                                                                                                                                                                                   26
fell overboard                                                                                                                                                                                                                                21
windsurfing                                                                                                                                                                                                                                   18
walking                                                                                                                                                                                                                                       15
sea disaster                                                                                                                                                                                                                                  14
canoeing                                                                                                                                                                                                                                      13
surf skiing                                                                                                                                                                                                                                   12
floating                                                                                                                                                                                                                                      12
rowing                                                                                                                                                                                                                                        12
surf-skiing                                                                                                                                                                                                                                   12
sponge diving                                                                                                                                                                                                                                 10
freediving                                                                                                                                                                                                                                    10
freedom swimming                                                                                                                                                                                                                               9
                                                                                                                                                                                                                                            ...
she was on a ship that was torpedoes & was in the water awaiting rescue                                                                                                                                                                        1
swimming / floating                                                                                                                                                                                                                            1
snorkeling on surface                                                                                                                                                                                                                          1
crouching in 2' of water                                                                                                                                                                                                                       1
standing / wading                                                                                                                                                                                                                              1
sea disaster : wreck of the carrie e. long                                                                                                                                                                                                     1
diving to untangle a crab trap line from boat's propeller                                                                                                                                                                                      1
sailboarding, fell into water 100 yards outside the breakwater                                                                                                                                                                                 1
leaving the water                                                                                                                                                                                                                              1
kayaking or wave skiing                                                                                                                                                                                                                        1
swimming after falling overboard                                                                                                                                                                                                               1
free diving for sinkers                                                                                                                                                                                                                        1
swimming to canoe                                                                                                                                                                                                                              1
diving alongsidethe steamship ranelagh                                                                                                                                                                                                         1
diving for sea urchins                                                                                                                                                                                                                         1
"boat accident"                                                                                                                                                                                                                                1
dutch merchant ship zaandam torpedoed  by the u-174 amidships, sank & dozens of survivors took to rafts & boats. one man, izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down       1
paddling rescue ski                                                                                                                                                                                                                            1
free diving, carrying speargun                                                                                                                                                                                                                 1
dived into the water                                                                                                                                                                                                                           1
diving for shells, saw shark circling wife near the surface, intercepted shark & it pulled him beneath the water                                                                                                                               1
swimming ashore after launch capsized                                                                                                                                                                                                          1
diving for trepang                                                                                                                                                                                                                             1
diving / filming                                                                                                                                                                                                                               1
holding shark on leader & dangling it above the water                                                                                                                                                                                          1
helping men land a shark                                                                                                                                                                                                                       1
removing shark from a net                                                                                                                                                                                                                      1
rowing toward snapper grounds                                                                                                                                                                                                                  1
a group of survivors on a raft for 17-days                                                                                                                                                                                                     1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                                                               1
Name: Activity, Length: 1145, dtype: int64

#### Then, all types of surf description in the surfing activity

In [11]:
def traducesurf(m, lexema="surf", resultado="surfing"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [12]:
data_clean['Activity'] = data_clean['Activity'].apply(traducesurf)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                                                     1195
surfing                                                                                                                                                                                                                                     1153
swimming                                                                                                                                                                                                                                     819
nan                                                                                                                                                                                                                                          527
bathing                                                                                                                                                                                                                                      153
wading                                                                                                                                                                                                                                       144
diving                                                                                                                                                                                                                                       123
standing                                                                                                                                                                                                                                      97
scuba diving                                                                                                                                                                                                                                  81
snorkeling                                                                                                                                                                                                                                    77
body boarding                                                                                                                                                                                                                                 57
swimming                                                                                                                                                                                                                                      47
boogie boarding                                                                                                                                                                                                                               44
pearl diving                                                                                                                                                                                                                                  32
treading water                                                                                                                                                                                                                                32
kayaking                                                                                                                                                                                                                                      28
free diving                                                                                                                                                                                                                                   26
fell overboard                                                                                                                                                                                                                                21
walking                                                                                                                                                                                                                                       15
sea disaster                                                                                                                                                                                                                                  14
canoeing                                                                                                                                                                                                                                      13
rowing                                                                                                                                                                                                                                        12
floating                                                                                                                                                                                                                                      12
sponge diving                                                                                                                                                                                                                                 10
freediving                                                                                                                                                                                                                                    10
diving for trochus                                                                                                                                                                                                                             9
freedom swimming                                                                                                                                                                                                                               9
sailing                                                                                                                                                                                                                                        9
fell into the water                                                                                                                                                                                                                            8
diving for abalone                                                                                                                                                                                                                             8
                                                                                                                                                                                                                                            ...
casting a net                                                                                                                                                                                                                                  1
sea disaster : wreck of the carrie e. long                                                                                                                                                                                                     1
swimming ashore after launch capsized                                                                                                                                                                                                          1
diving to untangle a crab trap line from boat's propeller                                                                                                                                                                                      1
sailboarding, fell into water 100 yards outside the breakwater                                                                                                                                                                                 1
leaving the water                                                                                                                                                                                                                              1
kayaking or wave skiing                                                                                                                                                                                                                        1
swimming after falling overboard                                                                                                                                                                                                               1
free diving for sinkers                                                                                                                                                                                                                        1
diving alongsidethe steamship ranelagh                                                                                                                                                                                                         1
diving for sea urchins                                                                                                                                                                                                                         1
dutch merchant ship zaandam torpedoed  by the u-174 amidships, sank & dozens of survivors took to rafts & boats. one man, izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down       1
paddling rescue ski                                                                                                                                                                                                                            1
free diving, carrying speargun                                                                                                                                                                                                                 1
dived into the water                                                                                                                                                                                                                           1
boeing 757 enroute from porta plata plunged into the sea                                                                                                                                                                                       1
washed overboard                                                                                                                                                                                                                               1
diving / filming                                                                                                                                                                                                                               1
holding shark on leader & dangling it above the water                                                                                                                                                                                          1
helping men land a shark                                                                                                                                                                                                                       1
removing shark from a net                                                                                                                                                                                                                      1
rowing toward snapper grounds                                                                                                                                                                                                                  1
swimming in waist-deep water                                                                                                                                                                                                                   1
a group of survivors on a raft for 17-days                                                                                                                                                                                                     1
kneeling in the water                                                                                                                                                                                                                          1
b-24 aircraft crashed  into the sea                                                                                                                                                                                                            1
diving, attempting to retrieve body of drowning victim wedged between rocks                                                                                                                                                                    1
swimming ashore from swamped 13-ft boat                                                                                                                                                                                                        1
chumming for white sharks                                                                                                                                                                                                                      1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                                                               1
Name: Activity, Length: 1032, dtype: int64

#### Then, a function for the swimming activity. That I considered different from the bathing, floating activity.

In [13]:
def traduceswim(m, lexema="swim", resultado="swimming"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [14]:
data_clean['Activity'] = data_clean['Activity'].apply(traduceswim)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                                                     1195
surfing                                                                                                                                                                                                                                     1153
swimming                                                                                                                                                                                                                                    1041
nan                                                                                                                                                                                                                                          527
bathing                                                                                                                                                                                                                                      153
wading                                                                                                                                                                                                                                       144
diving                                                                                                                                                                                                                                       123
standing                                                                                                                                                                                                                                      97
scuba diving                                                                                                                                                                                                                                  81
snorkeling                                                                                                                                                                                                                                    77
body boarding                                                                                                                                                                                                                                 57
boogie boarding                                                                                                                                                                                                                               44
pearl diving                                                                                                                                                                                                                                  32
treading water                                                                                                                                                                                                                                32
kayaking                                                                                                                                                                                                                                      28
free diving                                                                                                                                                                                                                                   26
fell overboard                                                                                                                                                                                                                                21
walking                                                                                                                                                                                                                                       15
sea disaster                                                                                                                                                                                                                                  14
canoeing                                                                                                                                                                                                                                      13
floating                                                                                                                                                                                                                                      12
rowing                                                                                                                                                                                                                                        12
sponge diving                                                                                                                                                                                                                                 10
freediving                                                                                                                                                                                                                                    10
sailing                                                                                                                                                                                                                                        9
diving for trochus                                                                                                                                                                                                                             9
paddle boarding                                                                                                                                                                                                                                8
diving for abalone                                                                                                                                                                                                                             8
fell into the water                                                                                                                                                                                                                            8
floating on his back                                                                                                                                                                                                                           7
                                                                                                                                                                                                                                            ...
anti-sabotage night dive exercise alongside destroyer (scuba diving)                                                                                                                                                                           1
in water with diving seabirds                                                                                                                                                                                                                  1
paddling in knee-deep water                                                                                                                                                                                                                    1
boat from the austrian ship elizabeth                                                                                                                                                                                                          1
diving on a wreck                                                                                                                                                                                                                              1
standing on his hands                                                                                                                                                                                                                          1
diving to untangle a crab trap line from boat's propeller                                                                                                                                                                                      1
washed overboard                                                                                                                                                                                                                               1
boat from city of naples capsized                                                                                                                                                                                                              1
leaving the water                                                                                                                                                                                                                              1
kayaking or wave skiing                                                                                                                                                                                                                        1
free diving for sinkers                                                                                                                                                                                                                        1
diving alongsidethe steamship ranelagh                                                                                                                                                                                                         1
standing in water with child in her arms                                                                                                                                                                                                       1
diving for sea urchins                                                                                                                                                                                                                         1
dutch merchant ship zaandam torpedoed  by the u-174 amidships, sank & dozens of survivors took to rafts & boats. one man, izzi, who drifted 83 days on a raft related that sharks attacked many men in the water when the ship went down       1
paddling rescue ski                                                                                                                                                                                                                            1
free diving, carrying speargun                                                                                                                                                                                                                 1
dived into the water                                                                                                                                                                                                                           1
boeing 757 enroute from porta plata plunged into the sea                                                                                                                                                                                       1
diving / filming                                                                                                                                                                                                                               1
helping men land a shark                                                                                                                                                                                                                       1
removing shark from a net                                                                                                                                                                                                                      1
rowing toward snapper grounds                                                                                                                                                                                                                  1
grabbed shark & threw it on deck                                                                                                                                                                                                               1
kneeling in the water                                                                                                                                                                                                                          1
b-24 aircraft crashed  into the sea                                                                                                                                                                                                            1
diving, attempting to retrieve body of drowning victim wedged between rocks                                                                                                                                                                    1
chumming for white sharks                                                                                                                                                                                                                      1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                                                               1
Name: Activity, Length: 875, dtype: int64

#### The next function is to group all the diving classes withing the diving activity.

In [15]:
def traducedive(m, lexema="div", resultado="diving"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [16]:
data_clean['Activity'] = data_clean['Activity'].apply(traducedive)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                 1195
surfing                                                                                                                                                                                                 1153
swimming                                                                                                                                                                                                1041
nan                                                                                                                                                                                                      527
diving                                                                                                                                                                                                   500
bathing                                                                                                                                                                                                  153
wading                                                                                                                                                                                                   144
standing                                                                                                                                                                                                  97
snorkeling                                                                                                                                                                                                77
body boarding                                                                                                                                                                                             57
boogie boarding                                                                                                                                                                                           44
treading water                                                                                                                                                                                            32
kayaking                                                                                                                                                                                                  28
fell overboard                                                                                                                                                                                            21
walking                                                                                                                                                                                                   15
sea disaster                                                                                                                                                                                              14
canoeing                                                                                                                                                                                                  13
floating                                                                                                                                                                                                  12
rowing                                                                                                                                                                                                    12
sailing                                                                                                                                                                                                    9
fell into the water                                                                                                                                                                                        8
paddle boarding                                                                                                                                                                                            8
boating                                                                                                                                                                                                    7
floating on his back                                                                                                                                                                                       7
playing                                                                                                                                                                                                    7
murder                                                                                                                                                                                                     6
boat                                                                                                                                                                                                       5
paddleskiing                                                                                                                                                                                               5
shipwreck                                                                                                                                                                                                  5
dangling feet in the water                                                                                                                                                                                 5
                                                                                                                                                                                                        ...
washed overboard from the barque mary eady                                                                                                                                                                 1
among 31 survivors of crew from the sampan fukulya maru (which reached thursday island in rowing boat) was a man whose arm had been bitten off by shark. the sampan wrecked west of mcarthur island        1
the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125.                                                                                                                       1
ship torpedoed 400 miles off the african coas. man was clinging to hatch cover                                                                                                                             1
playing                                                                                                                                                                                                    1
gathering shells                                                                                                                                                                                           1
bathing alongside us naval ship                                                                                                                                                                            1
nsb meshing                                                                                                                                                                                                1
washing his pig in preparation for a religious ceremony                                                                                                                                                    1
killing a shark                                                                                                                                                                                            1
jumped overboard from torpedoed panamanian freighter                                                                                                                                                       1
adrift on raft                                                                                                                                                                                             1
photographing sharks underwater using scuba                                                                                                                                                                1
copra vessel with 19 on board was wrecked in a squall                                                                                                                                                      1
slipped off rocks and fell into the water                                                                                                                                                                  1
rolled off raft                                                                                                                                                                                            1
boat capsized between o'ahu & molokai                                                                                                                                                                      1
bathing with her mother                                                                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                                                                           1
washing horses                                                                                                                                                                                             1
the 500-ton coastal trader polurrian foundered                                                                                                                                                             1
crouching in the water                                                                                                                                                                                     1
yacht gooney bird foundered, 4 survivors on raft                                                                                                                                                           1
playing with an air mattress                                                                                                                                                                               1
paddling outrigger canoe                                                                                                                                                                                   1
catching sardines                                                                                                                                                                                          1
floating                                                                                                                                                                                                   1
bodyboarding                                                                                                                                                                                               1
the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered                                                                                                         1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                           1
Name: Activity, Length: 717, dtype: int64

#### A lot of activities involved canoes, so I decided to group then within the canoeing actvity.

In [17]:
def traducecanoa(m, lexema="canoe", resultado="canoeing"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [18]:
data_clean['Activity'] = data_clean['Activity'].apply(traducecanoa)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                 1195
surfing                                                                                                                                                                                                 1153
swimming                                                                                                                                                                                                1041
nan                                                                                                                                                                                                      527
diving                                                                                                                                                                                                   500
bathing                                                                                                                                                                                                  153
wading                                                                                                                                                                                                   144
standing                                                                                                                                                                                                  97
snorkeling                                                                                                                                                                                                77
body boarding                                                                                                                                                                                             57
boogie boarding                                                                                                                                                                                           44
treading water                                                                                                                                                                                            32
kayaking                                                                                                                                                                                                  28
canoeing                                                                                                                                                                                                  25
fell overboard                                                                                                                                                                                            21
walking                                                                                                                                                                                                   15
sea disaster                                                                                                                                                                                              14
rowing                                                                                                                                                                                                    12
floating                                                                                                                                                                                                  12
sailing                                                                                                                                                                                                    9
paddle boarding                                                                                                                                                                                            8
fell into the water                                                                                                                                                                                        8
playing                                                                                                                                                                                                    7
floating on his back                                                                                                                                                                                       7
boating                                                                                                                                                                                                    7
murder                                                                                                                                                                                                     6
shipwreck                                                                                                                                                                                                  5
paddleskiing                                                                                                                                                                                               5
boat                                                                                                                                                                                                       5
dangling feet in the water                                                                                                                                                                                 5
                                                                                                                                                                                                        ...
standing / snorkeling                                                                                                                                                                                      1
adrift on raft                                                                                                                                                                                             1
washed overboard from the barque mary eady                                                                                                                                                                 1
among 31 survivors of crew from the sampan fukulya maru (which reached thursday island in rowing boat) was a man whose arm had been bitten off by shark. the sampan wrecked west of mcarthur island        1
the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125.                                                                                                                       1
ship torpedoed 400 miles off the african coas. man was clinging to hatch cover                                                                                                                             1
playing                                                                                                                                                                                                    1
gathering shells                                                                                                                                                                                           1
bathing alongside us naval ship                                                                                                                                                                            1
jumped overboard from torpedoed panamanian freighter                                                                                                                                                       1
crouching in the water                                                                                                                                                                                     1
fell from yardarm of british ship rover                                                                                                                                                                    1
washing horses                                                                                                                                                                                             1
paddle-boarding                                                                                                                                                                                            1
copra vessel with 19 on board was wrecked in a squall                                                                                                                                                      1
slipped off rocks and fell into the water                                                                                                                                                                  1
rolled off raft                                                                                                                                                                                            1
boat capsized between o'ahu & molokai                                                                                                                                                                      1
bathing with her mother                                                                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                                                                           1
photographing sharks underwater using scuba                                                                                                                                                                1
the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered                                                                                                         1
the 500-ton coastal trader polurrian foundered                                                                                                                                                             1
yacht gooney bird foundered, 4 survivors on raft                                                                                                                                                           1
playing with an air mattress                                                                                                                                                                               1
no details                                                                                                                                                                                                 1
catching sardines                                                                                                                                                                                          1
floating                                                                                                                                                                                                   1
bodyboarding                                                                                                                                                                                               1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                           1
Name: Activity, Length: 705, dtype: int64

#### A floating activity for all the people just floating on the water.

In [19]:
def traducefloat(m, lexema="float", resultado="floating"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [20]:
data_clean['Activity'] = data_clean['Activity'].apply(traducefloat)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                                                                                 1195
surfing                                                                                                                                                                                                 1153
swimming                                                                                                                                                                                                1041
nan                                                                                                                                                                                                      527
diving                                                                                                                                                                                                   500
bathing                                                                                                                                                                                                  153
wading                                                                                                                                                                                                   144
standing                                                                                                                                                                                                  97
snorkeling                                                                                                                                                                                                77
body boarding                                                                                                                                                                                             57
floating                                                                                                                                                                                                  47
boogie boarding                                                                                                                                                                                           44
treading water                                                                                                                                                                                            32
kayaking                                                                                                                                                                                                  28
canoeing                                                                                                                                                                                                  25
fell overboard                                                                                                                                                                                            21
walking                                                                                                                                                                                                   15
sea disaster                                                                                                                                                                                              14
rowing                                                                                                                                                                                                    12
sailing                                                                                                                                                                                                    9
fell into the water                                                                                                                                                                                        8
paddle boarding                                                                                                                                                                                            8
boating                                                                                                                                                                                                    7
playing                                                                                                                                                                                                    7
murder                                                                                                                                                                                                     6
shipwreck                                                                                                                                                                                                  5
boat                                                                                                                                                                                                       5
dangling feet in the water                                                                                                                                                                                 5
paddleskiing                                                                                                                                                                                               5
seine netting                                                                                                                                                                                              4
                                                                                                                                                                                                        ...
standing / snorkeling                                                                                                                                                                                      1
among 31 survivors of crew from the sampan fukulya maru (which reached thursday island in rowing boat) was a man whose arm had been bitten off by shark. the sampan wrecked west of mcarthur island        1
slipped off rocks and fell into the water                                                                                                                                                                  1
the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125.                                                                                                                       1
ship torpedoed 400 miles off the african coas. man was clinging to hatch cover                                                                                                                             1
playing                                                                                                                                                                                                    1
gathering shells                                                                                                                                                                                           1
bathing alongside us naval ship                                                                                                                                                                            1
nsb meshing                                                                                                                                                                                                1
washing his pig in preparation for a religious ceremony                                                                                                                                                    1
unknown, their unoccupied yawlboat was recovered                                                                                                                                                           1
hurricane & tidal wave                                                                                                                                                                                     1
killing a shark                                                                                                                                                                                            1
jumped overboard from torpedoed panamanian freighter                                                                                                                                                       1
rolled off raft                                                                                                                                                                                            1
boat capsized between o'ahu & molokai                                                                                                                                                                      1
bathing with her mother                                                                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                                                                           1
washing horses                                                                                                                                                                                             1
photographing sharks underwater using scuba                                                                                                                                                                1
the 500-ton coastal trader polurrian foundered                                                                                                                                                             1
yacht gooney bird foundered, 4 survivors on raft                                                                                                                                                           1
playing with an air mattress                                                                                                                                                                               1
no details                                                                                                                                                                                                 1
catching sardines                                                                                                                                                                                          1
bodyboarding                                                                                                                                                                                               1
the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered                                                                                                         1
crouching in the water                                                                                                                                                                                     1
adrift on raft                                                                                                                                                                                             1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                                                                                                                           1
Name: Activity, Length: 680, dtype: int64

#### A lot of activities decribed some kind of sailing, boats or others, those were all grouped in the activity sailing/boating

In [21]:
def traducesail(m):
    a=str(m).lower()
    for word in ["sailing", "boating", "travelling by boat", "boat", "sail"]:
        if word in a:
            return "sailing/boating"
    return a

In [22]:
data_clean['Activity'] = data_clean['Activity'].apply(traducesail)
data_clean["Activity"].value_counts()

fishing and other types                                                                               1195
surfing                                                                                               1153
swimming                                                                                              1041
nan                                                                                                    527
diving                                                                                                 500
bathing                                                                                                153
wading                                                                                                 144
sailing/boating                                                                                        105
standing                                                                                                97
snorkeling                                                                                              77
body boarding                                                                                           57
floating                                                                                                47
boogie boarding                                                                                         44
treading water                                                                                          32
kayaking                                                                                                28
canoeing                                                                                                25
fell overboard                                                                                          21
walking                                                                                                 15
sea disaster                                                                                            14
rowing                                                                                                  12
paddle boarding                                                                                          8
fell into the water                                                                                      8
playing                                                                                                  7
murder                                                                                                   6
paddleskiing                                                                                             5
shipwreck                                                                                                5
dangling feet in the water                                                                               5
body-boarding                                                                                            4
seine netting                                                                                            4
stand-up paddleboarding                                                                                  4
                                                                                                      ...
bathing alongside us naval ship                                                                          1
gathering shells                                                                                         1
playing                                                                                                  1
ship torpedoed 400 miles off the african coas. man was clinging to hatch cover                           1
the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125.                     1
washed overboard from the barque mary eady                                                               1
standing / snorkeling                                                                                    1
parachuted from balloon                                                                                  1
bathing close inshore                                                                                    1
boogie boarding, kicked at object in the water                                                           1
attempting to fix motor                                                                                  1
3-masted steel barque glenbank foundered during a cyclone                                                1
hurricane & tidal wave                                                                                   1
jumped overboard from torpedoed panamanian freighter                                                     1
copra vessel with 19 on board was wrecked in a squall                                                    1
crouching in the water                                                                                   1
the schooner elizabeth, bound from bluefields, nicaragua to the river port of san carlos foundered       1
bodyboarding                                                                                             1
catching sardines                                                                                        1
no details                                                                                               1
playing with an air mattress                                                                             1
yacht gooney bird foundered, 4 survivors on raft                                                         1
the 500-ton coastal trader polurrian foundered                                                           1
photographing sharks underwater using scuba                                                              1
washing horses                                                                                           1
grabbed shark & threw it on deck                                                                         1
bathing with her mother                                                                                  1
rolled off raft                                                                                          1
slipped off rocks and fell into the water                                                                1
the ss potlach was torpedoed & sunk by the u-153 on 27-jun-1942.                                         1
Name: Activity, Length: 602, dtype: int64

#### Also important to take into account all the attacks that happend because of a disaster. Plains that crashed in the sea, boats explosions, collisions, sunken ships ect. Those fell under the Sea/Air disaster activity

In [23]:
def traducedisaster(m):
    a=str(m).lower()
    for word in ["disast", "plane forced down", "foundering", "foundered", "ditched", "crash", "explosion", "exploded", "explode", "collided", "sank", "sink", "sunk", "accident", "collision", "concussion", "crack-up", "smash", "smashup", "wreck", "shipwreck", "capsized", "plunged into the sea", "aircraft went down", "aircraft down"]:
        if word in a:
            return "Sea/Air disaster"
    return a

In [24]:
data_clean['Activity'] = data_clean['Activity'].apply(traducedisaster)
data_clean["Activity"].value_counts()

fishing and other types                                                                      1195
surfing                                                                                      1153
swimming                                                                                     1041
nan                                                                                           527
diving                                                                                        500
Sea/Air disaster                                                                              163
bathing                                                                                       153
wading                                                                                        144
sailing/boating                                                                               105
standing                                                                                       97
snorkeling                                                                                     77
body boarding                                                                                  57
floating                                                                                       47
boogie boarding                                                                                44
treading water                                                                                 32
kayaking                                                                                       28
canoeing                                                                                       25
fell overboard                                                                                 21
walking                                                                                        15
rowing                                                                                         12
fell into the water                                                                             8
paddle boarding                                                                                 8
playing                                                                                         7
murder                                                                                          6
dangling feet in the water                                                                      5
paddleskiing                                                                                    5
splashing                                                                                       4
jumped into the water                                                                           4
stand-up paddleboarding                                                                         4
body-boarding                                                                                   4
                                                                                             ...
stuffing a shark into an automobile                                                             1
hunting sharks                                                                                  1
scientific research (dr. sonny gruber's student)                                                1
jumping in the waves                                                                            1
removing shark from tank in nightclub                                                           1
paddle-boarding                                                                                 1
crouching in the water                                                                          1
the 6015-ton british ship empire avocet was torpedoed by the german submarine u-125.            1
washed overboard from the barque mary eady                                                      1
standing / snorkeling                                                                           1
parachuted from balloon                                                                         1
bathing close inshore                                                                           1
boogie boarding, kicked at object in the water                                                  1
attempting to fix motor                                                                         1
hurricane & tidal wave                                                                          1
killing a shark                                                                                 1
jumped overboard from torpedoed panamanian freighter                                            1
bodyboarding                                                                                    1
captured allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks       1
catching sardines                                                                               1
no details                                                                                      1
playing with an air mattress                                                                    1
adrift on a 4'  raft for 32 days                                                                1
photographing sharks underwater using scuba                                                     1
washing horses                                                                                  1
grabbed shark & threw it on deck                                                                1
bathing with her mother                                                                         1
rolled off raft                                                                                 1
slipped off rocks and fell into the water                                                       1
helping friend land hooked shark                                                                1
Name: Activity, Length: 466, dtype: int64

#### Another function for the people that fell accidentaly into the water from a boat or bridge or any other surface.

In [25]:
def traducealagua(m):
    a=str(m).lower()
    for word in ["fell", "overboard", "jumped", "went over"]:
        if word in a:
            return "Fell into water/overboad"
    return a

In [26]:
data_clean['Activity'] = data_clean['Activity'].apply(traducealagua)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                               1195
surfing                                                                                                                                               1153
swimming                                                                                                                                              1041
nan                                                                                                                                                    527
diving                                                                                                                                                 500
sea/air disaster                                                                                                                                       163
bathing                                                                                                                                                153
wading                                                                                                                                                 144
sailing/boating                                                                                                                                        105
standing                                                                                                                                                97
Fell into water/overboad                                                                                                                                88
snorkeling                                                                                                                                              77
body boarding                                                                                                                                           57
floating                                                                                                                                                47
boogie boarding                                                                                                                                         44
treading water                                                                                                                                          32
kayaking                                                                                                                                                28
canoeing                                                                                                                                                25
walking                                                                                                                                                 15
rowing                                                                                                                                                  12
paddle boarding                                                                                                                                          8
playing                                                                                                                                                  7
murder                                                                                                                                                   6
dangling feet in the water                                                                                                                               5
paddleskiing                                                                                                                                             5
lifesaving drill                                                                                                                                         4
seine netting                                                                                                                                            4
kite boarding                                                                                                                                            4
body-boarding                                                                                                                                            4
stand-up paddleboarding                                                                                                                                  4
                                                                                                                                                      ...
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                           1
kneeling in the water                                                                                                                                    1
stuffing a shark into an automobile                                                                                                                      1
hunting sharks                                                                                                                                           1
scientific research (dr. sonny gruber's student)                                                                                                         1
watching the shark feeding on a dead pinniped                                                                                                            1
dropping anchor                                                                                                                                          1
captured allied soldiers were squeezed into 3' bamboo pig baskets & fed to waiting sharks                                                                1
jumping in the waves                                                                                                                                     1
removing shark from tank in nightclub                                                                                                                    1
standing / snorkeling                                                                                                                                    1
bathing close inshore                                                                                                                                    1
boogie boarding, kicked at object in the water                                                                                                           1
attempting to fix motor                                                                                                                                  1
hurricane & tidal wave                                                                                                                                   1
killing a shark                                                                                                                                          1
on december 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in silcily and southern italy, killing more than 100,000 people       1
crouching in the water                                                                                                                                   1
bodyboarding                                                                                                                                             1
catching sardines                                                                                                                                        1
no details                                                                                                                                               1
playing with an air mattress                                                                                                                             1
adrift on a 4'  raft for 32 days                                                                                                                         1
photographing sharks underwater using scuba                                                                                                              1
washing horses                                                                                                                                           1
grabbed shark & threw it on deck                                                                                                                         1
bathing with her mother                                                                                                                                  1
rolled off raft                                                                                                                                          1
paddle-boarding                                                                                                                                          1
helping friend land hooked shark                                                                                                                         1
Name: Activity, Length: 414, dtype: int64

#### Some of the oldest records described war or battle happenings. Those were gathered in the War/battle activity.

In [27]:
def traduceguerra(m):
    a=str(m).lower()
    for word in ["war", "torpedoed", "navy", "battle", "soldier", "soldiers", "torpedoes", "air force"]:
        if word in a:
            return "War/battle"
    return a

In [28]:
data_clean['Activity'] = data_clean['Activity'].apply(traduceguerra)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                               1195
surfing                                                                                                                                               1153
swimming                                                                                                                                              1041
nan                                                                                                                                                    527
diving                                                                                                                                                 500
sea/air disaster                                                                                                                                       163
bathing                                                                                                                                                153
wading                                                                                                                                                 144
sailing/boating                                                                                                                                        105
standing                                                                                                                                                97
fell into water/overboad                                                                                                                                88
snorkeling                                                                                                                                              77
body boarding                                                                                                                                           57
floating                                                                                                                                                47
boogie boarding                                                                                                                                         44
treading water                                                                                                                                          32
kayaking                                                                                                                                                28
canoeing                                                                                                                                                25
walking                                                                                                                                                 15
War/battle                                                                                                                                              15
rowing                                                                                                                                                  12
paddle boarding                                                                                                                                          8
playing                                                                                                                                                  7
murder                                                                                                                                                   6
paddleskiing                                                                                                                                             5
dangling feet in the water                                                                                                                               5
lifesaving drill                                                                                                                                         4
body-boarding                                                                                                                                            4
jumping                                                                                                                                                  4
seine netting                                                                                                                                            4
                                                                                                                                                      ...
moving a shark in a net                                                                                                                                  1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                           1
kneeling in the water                                                                                                                                    1
stuffing a shark into an automobile                                                                                                                      1
hunting sharks                                                                                                                                           1
scientific research (dr. sonny gruber's student)                                                                                                         1
dropping anchor                                                                                                                                          1
jumping in the waves                                                                                                                                     1
playing                                                                                                                                                  1
removing shark from tank in nightclub                                                                                                                    1
on december 28, 1908, an earthquake, followed by tsunamis, destroyed coastal towns in silcily and southern italy, killing more than 100,000 people       1
standing / snorkeling                                                                                                                                    1
bathing close inshore                                                                                                                                    1
boogie boarding, kicked at object in the water                                                                                                           1
attempting to fix motor                                                                                                                                  1
hurricane & tidal wave                                                                                                                                   1
killing a shark                                                                                                                                          1
crouching in the water                                                                                                                                   1
bodyboarding                                                                                                                                             1
catching sardines                                                                                                                                        1
no details                                                                                                                                               1
playing with an air mattress                                                                                                                             1
adrift on a 4'  raft for 32 days                                                                                                                         1
photographing sharks underwater using scuba                                                                                                              1
washing horses                                                                                                                                           1
grabbed shark & threw it on deck                                                                                                                         1
bathing with her mother                                                                                                                                  1
rolled off raft                                                                                                                                          1
paddle-boarding                                                                                                                                          1
helping friend land hooked shark                                                                                                                         1
Name: Activity, Length: 401, dtype: int64

#### Another important activity to be considered is the weather conditions. So a new function was defined for that category.

In [29]:
def traduceweather(m):
    a=str(m).lower()
    for word in ["tsunami", "earthquake", "storm", "seaquake", "oceanquake", "tidal wave"]:
        if word in a:
            return "Weather incidents"
    return a

In [30]:
data_clean['Activity'] = data_clean['Activity'].apply(traduceweather)
data_clean["Activity"].value_counts()

fishing and other types                                                           1195
surfing                                                                           1153
swimming                                                                          1041
nan                                                                                527
diving                                                                             500
sea/air disaster                                                                   163
bathing                                                                            153
wading                                                                             144
sailing/boating                                                                    105
standing                                                                            97
fell into water/overboad                                                            88
snorkeling                                                                          77
body boarding                                                                       57
floating                                                                            47
boogie boarding                                                                     44
treading water                                                                      32
kayaking                                                                            28
canoeing                                                                            25
war/battle                                                                          15
walking                                                                             15
rowing                                                                              12
paddle boarding                                                                      8
playing                                                                              7
murder                                                                               6
paddleskiing                                                                         5
dangling feet in the water                                                           5
seine netting                                                                        4
body-boarding                                                                        4
stand-up paddleboarding                                                              4
jumping                                                                              4
                                                                                  ...
walking in shallows                                                                  1
attempting to attract dolphins                                                       1
moving a shark in a net                                                              1
hauling dead shark aboard, when another shark leapt out of the water & bit him       1
kneeling in the water                                                                1
stuffing a shark into an automobile                                                  1
hunting sharks                                                                       1
treading for clams                                                                   1
jumping in the waves                                                                 1
removing shark from tank in nightclub                                                1
bodyboarding                                                                         1
gathering shells                                                                     1
playing                                                                              1
standing / snorkeling                                                                1
bathing close inshore                                                                1
boogie boarding, kicked at object in the water                                       1
attempting to fix motor                                                              1
killing a shark                                                                      1
crouching in the water                                                               1
catching sardines                                                                    1
paddle-boarding                                                                      1
no details                                                                           1
playing with an air mattress                                                         1
adrift on a 4'  raft for 32 days                                                     1
photographing sharks underwater using scuba                                          1
washing horses                                                                       1
grabbed shark & threw it on deck                                                     1
bathing with her mother                                                              1
rolled off raft                                                                      1
helping friend land hooked shark                                                     1
Name: Activity, Length: 399, dtype: int64

#### An important number of records talked about walking, standing, playing and other common human activities at the beach or near the sea.

In [31]:
def traducehumanm(m):
    a=str(m).lower()
    for word in ["wading", "standing", "walking", "crawling", "splashing", "playing", "jumping", "kneeling", "stamding"]:
        if word in a:
            return "Walk/stand/play & others"
    return a

In [32]:
data_clean['Activity'] = data_clean['Activity'].apply(traducehumanm)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                         1195
surfing                                                                                                                                         1153
swimming                                                                                                                                        1041
nan                                                                                                                                              527
diving                                                                                                                                           500
Walk/stand/play & others                                                                                                                         330
sea/air disaster                                                                                                                                 163
bathing                                                                                                                                          153
sailing/boating                                                                                                                                  105
fell into water/overboad                                                                                                                          88
snorkeling                                                                                                                                        77
body boarding                                                                                                                                     57
floating                                                                                                                                          47
boogie boarding                                                                                                                                   44
treading water                                                                                                                                    32
kayaking                                                                                                                                          28
canoeing                                                                                                                                          25
war/battle                                                                                                                                        15
rowing                                                                                                                                            12
paddle boarding                                                                                                                                    8
murder                                                                                                                                             6
dangling feet in the water                                                                                                                         5
paddleskiing                                                                                                                                       5
body-boarding                                                                                                                                      4
lifesaving drill                                                                                                                                   4
stand-up paddleboarding                                                                                                                            4
kite boarding                                                                                                                                      4
seine netting                                                                                                                                      4
weather incidents                                                                                                                                  3
their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
                                                                                                                                                ...
put foot inside a landed & supposedly dead shark                                                                                                   1
hunting seals                                                                                                                                      1
male                                                                                                                                               1
spent 8 days in dinghy                                                                                                                             1
attempting to attract dolphins                                                                                                                     1
moving a shark in a net                                                                                                                            1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
hunting sharks                                                                                                                                     1
scientific research (dr. sonny gruber's student)                                                                                                   1
watching the shark feeding on a dead pinniped                                                                                                      1
washing cooking pans                                                                                                                               1
wakeboarding                                                                                                                                       1
attempting to fix motor                                                                                                                            1
dropping anchor                                                                                                                                    1
killing a shark                                                                                                                                    1
crouching in the water                                                                                                                             1
bodyboarding                                                                                                                                       1
catching sardines                                                                                                                                  1
no details                                                                                                                                         1
adrift on a 4'  raft for 32 days                                                                                                                   1
photographing sharks underwater using scuba                                                                                                        1
washing horses                                                                                                                                     1
grabbed shark & threw it on deck                                                                                                                   1
bathing with her mother                                                                                                                            1
rolled off raft                                                                                                                                    1
paddle-boarding                                                                                                                                    1
removing shark from tank in nightclub                                                                                                              1
pulling anchor                                                                                                                                     1
treading for clams                                                                                                                                 1
helping friend land hooked shark                                                                                                                   1
Name: Activity, Length: 341, dtype: int64

#### This function merged all the floating, bathing and other kind of relaxing on the water.

In [33]:
def traducebath(m):
    a=str(m).lower()
    for word in ["bathing", "floating", "float", "relaxing", "relax", "treading", "tread", "bather", "leaving the water"]:
        if word in a:
            return "bathing/floating"
    return a

In [34]:
data_clean['Activity'] = data_clean['Activity'].apply(traducebath)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                         1195
surfing                                                                                                                                         1153
swimming                                                                                                                                        1041
nan                                                                                                                                              527
diving                                                                                                                                           500
walk/stand/play & others                                                                                                                         330
bathing/floating                                                                                                                                 259
sea/air disaster                                                                                                                                 163
sailing/boating                                                                                                                                  105
fell into water/overboad                                                                                                                          88
snorkeling                                                                                                                                        77
body boarding                                                                                                                                     57
boogie boarding                                                                                                                                   44
kayaking                                                                                                                                          28
canoeing                                                                                                                                          25
war/battle                                                                                                                                        15
rowing                                                                                                                                            12
paddle boarding                                                                                                                                    8
murder                                                                                                                                             6
paddleskiing                                                                                                                                       5
dangling feet in the water                                                                                                                         5
stand-up paddleboarding                                                                                                                            4
kite boarding                                                                                                                                      4
seine netting                                                                                                                                      4
lifesaving drill                                                                                                                                   4
body-boarding                                                                                                                                      4
weather incidents                                                                                                                                  3
competing in the woodvale atlantic rowing race                                                                                                     3
sculling                                                                                                                                           3
their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
                                                                                                                                                ...
abandoning burning ship captain george in raging seas                                                                                              1
put foot inside a landed & supposedly dead shark                                                                                                   1
hunting seals                                                                                                                                      1
male                                                                                                                                               1
attempting to attract dolphins                                                                                                                     1
crouching in the water                                                                                                                             1
moving a shark in a net                                                                                                                            1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
hunting sharks                                                                                                                                     1
scientific research (dr. sonny gruber's student)                                                                                                   1
watching the shark feeding on a dead pinniped                                                                                                      1
removing shark from a net                                                                                                                          1
harpooning turtles                                                                                                                                 1
rowing a dinghy                                                                                                                                    1
washing cooking pans                                                                                                                               1
bending over                                                                                                                                       1
wakeboarding                                                                                                                                       1
dropping anchor                                                                                                                                    1
pulling anchor                                                                                                                                     1
removing shark from tank in nightclub                                                                                                              1
paddle-boarding                                                                                                                                    1
rolled off raft                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                   1
washing horses                                                                                                                                     1
photographing sharks underwater using scuba                                                                                                        1
adrift on a 4'  raft for 32 days                                                                                                                   1
no details                                                                                                                                         1
catching sardines                                                                                                                                  1
bodyboarding                                                                                                                                       1
helping friend land hooked shark                                                                                                                   1
Name: Activity, Length: 315, dtype: int64

#### Logically, surfing is the most common activities with shark attacks, so I created a new function to gather all the other water sports not so commonly involved in shark attacks.

In [35]:
def traducesports(m):
    a=str(m).lower()
    for word in ["jet ski", "sup foil boarding", "resting on body board", "water skiing", "skiing", "body boarding", "boogie boarding", "body-boarding", "kite boarding", "stand-up padleboarding", "SUP", "paddle boarding", "bodyboarding", "riding waves on board", "lying on board"]:
        if word in a:
            return "Other watersports"
    return a

In [36]:
data_clean['Activity'] = data_clean['Activity'].apply(traducesports)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                         1195
surfing                                                                                                                                         1153
swimming                                                                                                                                        1041
nan                                                                                                                                              527
diving                                                                                                                                           500
walk/stand/play & others                                                                                                                         330
bathing/floating                                                                                                                                 259
sea/air disaster                                                                                                                                 163
Other watersports                                                                                                                                132
sailing/boating                                                                                                                                  105
fell into water/overboad                                                                                                                          88
snorkeling                                                                                                                                        77
kayaking                                                                                                                                          28
canoeing                                                                                                                                          25
war/battle                                                                                                                                        15
rowing                                                                                                                                            12
murder                                                                                                                                             6
dangling feet in the water                                                                                                                         5
stand-up paddleboarding                                                                                                                            4
lifesaving drill                                                                                                                                   4
seine netting                                                                                                                                      4
.                                                                                                                                                  3
escaping from alacatraz                                                                                                                            3
competing in the woodvale atlantic rowing race                                                                                                     3
unknown                                                                                                                                            3
shark watching                                                                                                                                     3
weather incidents                                                                                                                                  3
tagging sharks                                                                                                                                     3
their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
sculling                                                                                                                                           3
                                                                                                                                                ...
bitten while cutting shark from net                                                                                                                1
removing shark from a net                                                                                                                          1
watching the shark feeding on a dead pinniped                                                                                                      1
scientific research (dr. sonny gruber's student)                                                                                                   1
hunting sharks                                                                                                                                     1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
moving a shark in a net                                                                                                                            1
attempting to attract dolphins                                                                                                                     1
spent 8 days in dinghy                                                                                                                             1
male                                                                                                                                               1
hunting seals                                                                                                                                      1
put foot inside a landed & supposedly dead shark                                                                                                   1
abandoning burning ship captain george in raging seas                                                                                              1
dragging stranded shark into deeper water                                                                                                          1
no details                                                                                                                                         1
harpooning turtles                                                                                                                                 1
rowing a dinghy                                                                                                                                    1
washing cooking pans                                                                                                                               1
bending over                                                                                                                                       1
wakeboarding                                                                                                                                       1
dropping anchor                                                                                                                                    1
pulling anchor                                                                                                                                     1
removing shark from tank in nightclub                                                                                                              1
paddle-boarding                                                                                                                                    1
rolled off raft                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                   1
washing horses                                                                                                                                     1
photographing sharks underwater using scuba                                                                                                        1
adrift on a 4'  raft for 32 days                                                                                                                   1
helping friend land hooked shark                                                                                                                   1
Name: Activity, Length: 301, dtype: int64

#### As we become more species/animal conscious, we try to help injured or in danger animals and that activity results with a big number of people injured trying to help sharks. Even if the shark is thankfull for the need, any movement can result in an injury.

In [37]:
def traducehelpshark(m):
    a=str(m).lower()
    for word in ["removing shark from a net", "removing shark from a trap", "caught in net", "injured shark", "stranded", "grounded", "beached", "net", "land a shark"]:
        if word in a:
            return "Helping sharks"
    return a

In [38]:
data_clean['Activity'] = data_clean['Activity'].apply(traducehelpshark)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                         1195
surfing                                                                                                                                         1153
swimming                                                                                                                                        1041
nan                                                                                                                                              527
diving                                                                                                                                           500
walk/stand/play & others                                                                                                                         330
bathing/floating                                                                                                                                 259
sea/air disaster                                                                                                                                 163
other watersports                                                                                                                                132
sailing/boating                                                                                                                                  105
fell into water/overboad                                                                                                                          88
snorkeling                                                                                                                                        77
Helping sharks                                                                                                                                    34
kayaking                                                                                                                                          28
canoeing                                                                                                                                          25
war/battle                                                                                                                                        15
rowing                                                                                                                                            12
murder                                                                                                                                             6
dangling feet in the water                                                                                                                         5
stand-up paddleboarding                                                                                                                            4
lifesaving drill                                                                                                                                   4
.                                                                                                                                                  3
escaping from alacatraz                                                                                                                            3
sculling                                                                                                                                           3
unknown                                                                                                                                            3
competing in the woodvale atlantic rowing race                                                                                                     3
weather incidents                                                                                                                                  3
tagging sharks                                                                                                                                     3
shark watching                                                                                                                                     3
their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
                                                                                                                                                ...
hunting sharks                                                                                                                                     1
attempting to fix motor                                                                                                                            1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
attempting to attract dolphins                                                                                                                     1
spent 8 days in dinghy                                                                                                                             1
male                                                                                                                                               1
hunting seals                                                                                                                                      1
put foot inside a landed & supposedly dead shark                                                                                                   1
abandoning burning ship captain george in raging seas                                                                                              1
feeding prawns to captive sharks                                                                                                                   1
harpooning turtles                                                                                                                                 1
rowing a dinghy                                                                                                                                    1
washing cooking pans                                                                                                                               1
bending over                                                                                                                                       1
wakeboarding                                                                                                                                       1
dropping anchor                                                                                                                                    1
pulling anchor                                                                                                                                     1
removing shark from tank in nightclub                                                                                                              1
paddle-boarding                                                                                                                                    1
rolled off raft                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                   1
washing horses                                                                                                                                     1
photographing sharks underwater using scuba                                                                                                        1
adrift on a 4'  raft for 32 days                                                                                                                   1
no details                                                                                                                                         1
catching sardines                                                                                                                                  1
murdered                                                                                                                                           1
crouching in the water                                                                                                                             1
killing a shark                                                                                                                                    1
helping friend land hooked shark                                                                                                                   1
Name: Activity, Length: 273, dtype: int64

#### The documentation said that sharks are not naturally agressive, the bite when they are curious with an object (can be a human or other) and when they feel threatened. So all attack to a shark will result in a human injury or with an attack in return.

In [39]:
def traduceattack(m):
    a=str(m).lower()
    for word in ["spearing", "pulling shark from the water", "wrangling a shark", "to ride a shark", "harassing", "killing sharks", "killing sharks", "kill shark", "kill sharks", "attack a shark", "attacking a shark", "killing a shark", "chase shark"]:
        if word in a:
            return "Attacking sharks"
    return a

In [40]:
data_clean['Activity'] = data_clean['Activity'].apply(traduceattack)
data_clean["Activity"].value_counts()

fishing and other types                                                           1195
surfing                                                                           1153
swimming                                                                          1041
nan                                                                                527
diving                                                                             500
walk/stand/play & others                                                           330
bathing/floating                                                                   259
sea/air disaster                                                                   163
other watersports                                                                  132
sailing/boating                                                                    105
fell into water/overboad                                                            88
snorkeling                                                                          77
helping sharks                                                                      34
kayaking                                                                            28
canoeing                                                                            25
war/battle                                                                          15
rowing                                                                              12
Attacking sharks                                                                     7
murder                                                                               6
dangling feet in the water                                                           5
lifesaving drill                                                                     4
stand-up paddleboarding                                                              4
escaping from alacatraz                                                              3
unknown                                                                              3
shark watching                                                                       3
competing in the woodvale atlantic rowing race                                       3
tagging sharks                                                                       3
weather incidents                                                                    3
sculling                                                                             3
.                                                                                    3
                                                                                  ...
taking wife to beach & about 1 m from the shore                                      1
scientific research (dr. sonny gruber's student)                                     1
bending over                                                                         1
hunting sharks                                                                       1
hauling dead shark aboard, when another shark leapt out of the water & bit him       1
attempting to attract dolphins                                                       1
spent 8 days in dinghy                                                               1
male                                                                                 1
hunting seals                                                                        1
put foot inside a landed & supposedly dead shark                                     1
abandoning burning ship captain george in raging seas                                1
feeding prawns to captive sharks                                                     1
harpooning turtles                                                                   1
rowing a dinghy                                                                      1
washing cooking pans                                                                 1
wakeboarding                                                                         1
attempting to fix motor                                                              1
dropping anchor                                                                      1
pulling anchor                                                                       1
removing shark from tank in nightclub                                                1
paddle-boarding                                                                      1
rolled off raft                                                                      1
grabbed shark & threw it on deck                                                     1
washing horses                                                                       1
photographing sharks underwater using scuba                                          1
adrift on a 4'  raft for 32 days                                                     1
no details                                                                           1
catching sardines                                                                    1
crouching in the water                                                               1
helping friend land hooked shark                                                     1
Name: Activity, Length: 267, dtype: int64

#### Many records had no details... Even though I was probably going to delete it, I decided the create the function in order to know how many records were there.

In [41]:
def traducenodetail(m):
    a=str(m).lower()
    for word in ["nan", "no details", "no detail", "unknown"]:
        if word in a:
            return "no details"
    return a

In [42]:
data_clean['Activity'] = data_clean['Activity'].apply(traducenodetail)
data_clean["Activity"].value_counts()

fishing and other types                                                                                                                         1195
surfing                                                                                                                                         1153
swimming                                                                                                                                        1041
no details                                                                                                                                       533
diving                                                                                                                                           500
walk/stand/play & others                                                                                                                         330
bathing/floating                                                                                                                                 259
sea/air disaster                                                                                                                                 163
other watersports                                                                                                                                132
sailing/boating                                                                                                                                  105
fell into water/overboad                                                                                                                          88
snorkeling                                                                                                                                        77
helping sharks                                                                                                                                    34
kayaking                                                                                                                                          28
canoeing                                                                                                                                          25
war/battle                                                                                                                                        15
rowing                                                                                                                                            12
attacking sharks                                                                                                                                   7
murder                                                                                                                                             6
dangling feet in the water                                                                                                                         5
stand-up paddleboarding                                                                                                                            4
lifesaving drill                                                                                                                                   4
their 9 m launch was run down by a 25,000-ton japanese freighter  on the night of 3-11-1977 & they drifted, clinging to an icebox for 2 days       3
shark watching                                                                                                                                     3
weather incidents                                                                                                                                  3
sculling                                                                                                                                           3
tagging sharks                                                                                                                                     3
.                                                                                                                                                  3
competing in the woodvale atlantic rowing race                                                                                                     3
escaping from alacatraz                                                                                                                            3
                                                                                                                                                ...
gathering shells                                                                                                                                   1
taking wife to beach & about 1 m from the shore                                                                                                    1
attempting to fix motor                                                                                                                            1
crouching in the water                                                                                                                             1
scientific research (dr. sonny gruber's student)                                                                                                   1
hunting sharks                                                                                                                                     1
hauling dead shark aboard, when another shark leapt out of the water & bit him                                                                     1
attempting to attract dolphins                                                                                                                     1
spent 8 days in dinghy                                                                                                                             1
male                                                                                                                                               1
hunting seals                                                                                                                                      1
put foot inside a landed & supposedly dead shark                                                                                                   1
abandoning burning ship captain george in raging seas                                                                                              1
towing her sister on plastic ski board                                                                                                             1
harpooning turtles                                                                                                                                 1
rowing a dinghy                                                                                                                                    1
washing cooking pans                                                                                                                               1
bending over                                                                                                                                       1
wakeboarding                                                                                                                                       1
dropping anchor                                                                                                                                    1
pulling anchor                                                                                                                                     1
removing shark from tank in nightclub                                                                                                              1
paddle-boarding                                                                                                                                    1
rolled off raft                                                                                                                                    1
grabbed shark & threw it on deck                                                                                                                   1
washing horses                                                                                                                                     1
photographing sharks underwater using scuba                                                                                                        1
adrift on a 4'  raft for 32 days                                                                                                                   1
catching sardines                                                                                                                                  1
helping friend land hooked shark                                                                                                                   1
Name: Activity, Length: 263, dtype: int64

#### A lot of people were attacked during working or studying activities. A new function was created for them

In [43]:
def traducework(m):
    a=str(m).lower()
    for word in ["working", "filming", "film", "documentary", "tagging sharks", "research", "measuring", "collecting"]:
        if word in a:
            return "working/studying"
    return a

#### After creating all of the functions above, I had a clearer idea of the information contained in my data set, and that, really helped me to decide the next steps. Some activities did not have enough number of records to be taken into account. So I decided to keep only the top 20 activities by number of records.

In [44]:
data_clean['Activity'] = data_clean['Activity'].apply(traducework)
data_clean["Activity"].value_counts().head(20)

fishing and other types     1195
surfing                     1153
swimming                    1041
no details                   533
diving                       500
walk/stand/play & others     330
bathing/floating             259
sea/air disaster             163
other watersports            132
sailing/boating              105
fell into water/overboad      88
snorkeling                    77
helping sharks                34
kayaking                      28
canoeing                      25
working/studying              19
war/battle                    15
rowing                        12
attacking sharks               7
murder                         6
Name: Activity, dtype: int64

#### I defined a list with the activities I was going to keep and them start working with that new data set.

In [45]:
list_activities = ["fishing and other types", "surfing", "swimming", "diving", "walk/stand/play & others", "bathing/floating", "sea/air disaster", "other watersports", "saling/boating",  "snorkeling", "helping sharks", "kayaking", "canoeing", "workin/studying", "war/battle"]

In [46]:
data_clean2 = data_clean[data_clean["Activity"].isin(list_activities)]
display(data_clean2)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,5989
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,fishing and other types,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN,5988
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,male,M,60s,Minor injury to arm,N,15h15,3' to 4' shark,5987
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,Late afternoon,NaN,5983
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
21,2016.07.28.R,28-Jul-16,2016,Unprovoked,CHINA,Hong Kong,NaN,swimming,Justus Franz,M,72,Lacerations to leg,N,NaN,NaN,5972
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,kayaking,Ian Watkins,M,NaN,"No injury, shark nudged kayak repeatedly",N,NaN,White shark,5971
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",fishing and other types,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'",5970
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
25,2016.07.24,24-Jul-16,2016,Unprovoked,JAPAN,Kochi Prefecture,Irino Beach,surfing,male,M,29,Lacerations to left leg,N,19h05,NaN,5968
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,fishing and other types,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'",5966
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",fishing and other types,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,After noon,"reef shark, 1m",5965
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,fishing and other types,Occupant: Ben Raines,NaN,NaN,"No injury, shark bit trolling motor",N,NaN,"Tiger shark, 10'",5964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5955,ND.0038,1941-1942,0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,swimming,male,M,13 or 14,"FATAL, left leg bitten with severe blood loss",Y,Afternoon,Bull shark,38
5956,ND.0037,1940 - 1950,0,Unprovoked,SAUDI ARABIA,Eastern Province,East of the Ras Tanura-Jubail area,diving,a pearl diver,M,NaN,"FATAL, died of sepsis",Y,NaN,"""a black-tipped shark""",37
5957,ND.0036,1940 - 1950,0,Unprovoked,SAUDI ARABIA,Eastern Province,East of the Ras Tanura-Jubail area,diving,a fisherman / diver,M,NaN,Buttocks bitten,N,NaN,6' shark,36
5958,ND.0035,1940 - 1950,0,Unprovoked,SAUDI ARABIA,Eastern Province,East of the Ras Tanura-Jubail area,diving,a pearl diver,M,NaN,"Foot lacerated, surgically amputated",N,NaN,NaN,35
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,swimming,male,M,NaN,Shark bumped him,N,NaN,NaN,31
5963,ND.0030,Before 1905,0,Unprovoked,BURMA,NaN,NaN,bathing/floating,male,M,NaN,Fatal x 2,Y,NaN,NaN,30
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,fishing and other types,Occupant: Mr. Maciotta,M,NaN,No injury to occupant; shark capsized boat,N,NaN,White shark,29
5965,ND.0027,No date,0,Unprovoked,GREECE,Dodecanese Islands,Symi Island,diving,Psarofa-gomenes,M,NaN,Head bitten,N,NaN,NaN,28
5966,ND.0026,Early 1930s,0,Unprovoked,BELIZE,NaN,NaN,walk/stand/play & others,a servant,M,16,FATAL,Y,NaN,12' tiger shark,27
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,swimming,NaN,NaN,NaN,FATAL,Y,NaN,NaN,25
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,walk/stand/play & others,Madelaine Dalton,F,NaN,Ankle bitten,N,NaN,NaN,24
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,diving,Jaringoorli,M,NaN,Lacerations to thigh,N,NaN,NaN,23
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,Indian boy,M,NaN,"FATAL, leg severed",Y,NaN,NaN,22
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",fishing and other types,James Kelley,M,NaN,2-inch lacerations,N,NaN,NaN,20
5974,ND.0018,Before 1911,0,Unprovoked,VIETNAM,Ba Ria-Vung Tau Province,V?ng T�u,swimming,crewman,M,NaN,Foot bitten,N,NaN,NaN,19
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,male,M,NaN,FATAL,Y,NaN,NaN,18
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,bathing/floating,male,M,NaN,FATAL,Y,NaN,NaN,17
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,canoeing,20 Fijians,NaN,NaN,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN,16
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,swimming,"""youthful male""",M,NaN,"""Lost leg""",N,NaN,NaN,15
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,fishing and other types,a native fisherman,M,NaN,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN,14
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,walk/stand/play & others,a young Scotsman,M,NaN,"FATAL, leg stripped of flesh",Y,NaN,NaN,13
5981,ND.0011,Before 1911,0,Unprovoked,ASIA?,NaN,NaN,swimming,Mr. Masury,M,NaN,Foot severed,N,NaN,NaN,12
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,boy,M,NaN,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,10
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointer,9
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointers,8
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,7
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,diving,male,M,NaN,FATAL,Y,NaN,NaN,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,4
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,2

#### After cleaning the activities column, it was time to clean the countries column. That was easier.

In [47]:
data_clean2["Country"].value_counts()

USA                       1874
AUSTRALIA                 1043
SOUTH AFRICA               483
NEW ZEALAND                105
PAPUA NEW GUINEA            98
BRAZIL                      87
BAHAMAS                     82
MEXICO                      68
ITALY                       54
REUNION                     52
FIJI                        46
NEW CALEDONIA               43
PHILIPPINES                 41
MOZAMBIQUE                  39
SPAIN                       32
EGYPT                       30
CUBA                        28
PANAMA                      24
INDIA                       24
SOLOMON ISLANDS             22
HONG KONG                   21
CROATIA                     21
GREECE                      19
FRENCH POLYNESIA            19
JAPAN                       17
INDONESIA                   15
JAMAICA                     14
IRAN                        14
TONGA                       13
PACIFIC OCEAN               13
                          ...
BANGLADESH                   1
Sierra Leone                 1
MEXICO                       1
KUWAIT                       1
RED SEA?                     1
ASIA?                        1
BRITISH WEST INDIES          1
GEORGIA                      1
TUVALU                       1
NORWAY                       1
NORTH SEA                    1
PACIFIC OCEAN                1
St Helena                    1
NORTH ATLANTIC OCEAN         1
ITALY / CROATIA              1
INDIAN OCEAN?                1
ALGERIA                      1
CEYLON (SRI LANKA)           1
GHANA                        1
SUDAN?                       1
SYRIA                        1
GUATEMALA                    1
ANGOLA                       1
BRITISH VIRGIN ISLANDS       1
MAYOTTE                      1
CURACAO                      1
ANTIGUA                      1
CAYMAN ISLANDS               1
DJIBOUTI                     1
ARGENTINA                    1
Name: Country, Length: 177, dtype: int64

#### I decided to keep the countries where more than 30 records were registered... ¡Spain among them! 😱

In [48]:
data_clean2 = data_clean2.groupby('Country').filter(lambda x : len(x)>30)
display(data_clean2)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,5989
5,2016.09.15.R,15-Sep-16,2016,Boat,AUSTRALIA,Western Australia,Bunbury,fishing and other types,Occupant: Ben Stratton,NaN,NaN,Shark rammed boat. No injury to occupant,N,NaN,NaN,5988
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,male,M,60s,Minor injury to arm,N,15h15,3' to 4' shark,5987
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,Late afternoon,NaN,5983
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
22,2016.07.28,28-Jul-16,2016,Boat,AUSTRALIA,Western Australia,Near Albany,kayaking,Ian Watkins,M,NaN,"No injury, shark nudged kayak repeatedly",N,NaN,White shark,5971
23,2016.07.27,27-Jul-16,2016,Provoked,USA,Florida,"Florida Keys, Monroe County",fishing and other types,Warren Sapp,M,43,Laceration to left forearm PROVOKED INCIDENT,N,NaN,"Nurse shark, 4'",5970
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,fishing and other types,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'",5966
28,2016.07.20,20-Jul-16,2016,Provoked,AUSTRALIA,Queensland,"20 k off The Spit, off the Gold Coast",fishing and other types,Scott van Burck,M,31,Laceration to left calf from hooked shark PROV...,N,After noon,"reef shark, 1m",5965
29,2016.07.17,17-Jul-16,2016,Boat,USA,Alabama,8 miles off Mobile,fishing and other types,Occupant: Ben Raines,NaN,NaN,"No injury, shark bit trolling motor",N,NaN,"Tiger shark, 10'",5964
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,female,F,9,Minor injury to leg,N,1300,NaN,5963
32,2016.07.15,15-Jul-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",swimming,male,M,NaN,Puncture wounds to foot,N,NaN,NaN,5961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5922,ND.0081,"No date, Before 1963",0,Invalid,USA,Hawaii,"Portlock, Oahu",diving,Val Valentine,M,NaN,A 4.3 m [14'] shark made threat display. No in...,N,NaN,NaN,71
5923,ND.0078,"No date, Before 1902",0,Unprovoked,USA,Florida,"Mosquito Inlet (Ponce Inlet), Volusia County",canoeing,male,M,NaN,FATAL,Y,NaN,NaN,70
5925,ND.0075,"No date, Before 1963",0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,NaN,Calf removed,N,NaN,0.9 m [3'] shark,68
5926,ND.0074,"No date, After August 1926 and before 1936",0,Unprovoked,AUSTRALIA,Western Australia,Cossack Creek,diving,Ted Luck,M,NaN,Leg bitten,N,NaN,NaN,67
5928,ND.0069,Before 1962,0,Unprovoked,FIJI,NaN,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,65
5929,ND.0068,Before 1962,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,diving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",64
5937,ND.0058,Before 1958,0,Unprovoked,FIJI,Kadavu Island Group,"18.8S, 178.25E",fishing and other types,Fijian girl,F,NaN,"""Severely injured when fish were seized by shark""",N,NaN,NaN,56
5939,ND.0056,Before 1958,0,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",walk/stand/play & others,Horton Chase,M,NaN,Abrasions & bruises hip to ankle,N,NaN,NaN,54
5940,ND.0055,Before 1958,0,Provoked,BAHAMAS,Andros Islands,Middle Bight,diving,John Fenton,M,NaN,Shark bit diver's sleeve after he patted it on...,N,NaN,"Nurse shark, 2.1 m [7']",53
5951,ND.0042,"""Before the war""",0,Unprovoked,AUSTRALIA,Torres Strait,Thursday Island?,diving,Mortakee,M,NaN,Head bitten,N,NaN,NaN,42
5962,ND.0031,World War II,0,Sea Disaster,PAPUA NEW GUINEA,Madang Province,Off Lae,swimming,male,M,NaN,Shark bumped him,N,NaN,NaN,31
5964,ND.0028,A few years before 1938,0,Boat,ITALY,Adriatic Sea,NaN,fishing and other types,Occupant: Mr. Maciotta,M,NaN,No injury to occupant; shark capsized boat,N,NaN,White shark,29
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,swimming,NaN,NaN,NaN,FATAL,Y,NaN,NaN,25
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,walk/stand/play & others,Madelaine Dalton,F,NaN,Ankle bitten,N,NaN,NaN,24
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,diving,Jaringoorli,M,NaN,Lacerations to thigh,N,NaN,NaN,23
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,Indian boy,M,NaN,"FATAL, leg severed",Y,NaN,NaN,22
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",fishing and other types,James Kelley,M,NaN,2-inch lacerations,N,NaN,NaN,20
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,male,M,NaN,FATAL,Y,NaN,NaN,18
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,bathing/floating,male,M,NaN,FATAL,Y,NaN,NaN,17
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,canoeing,20 Fijians,NaN,NaN,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN,16
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,swimming,"""youthful male""",M,NaN,"""Lost leg""",N,NaN,NaN,15
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,fishing and other types,a native fisherman,M,NaN,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN,14
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,walk/stand/play & others,a young Scotsman,M,NaN,"FATAL, leg stripped of flesh",Y,NaN,NaN,13
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,boy,M,NaN,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,10
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointer,9
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointers,8
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,7
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,diving,male,M,NaN,FATAL,Y,NaN,NaN,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,4

In [49]:
data_clean2["Country"].value_counts()

USA                 1874
AUSTRALIA           1043
SOUTH AFRICA         483
NEW ZEALAND          105
PAPUA NEW GUINEA      98
BRAZIL                87
BAHAMAS               82
MEXICO                68
ITALY                 54
REUNION               52
FIJI                  46
NEW CALEDONIA         43
PHILIPPINES           41
MOZAMBIQUE            39
SPAIN                 32
Name: Country, dtype: int64

#### Before definitely deleting othe types of attacks other than unprovoked, I decided to analyze that column a little bit. Unprovoked has more than 3000 records already, so other types, even if unprovoked attacks, were not going to change a lot my analysis.

In [50]:
data_clean2["Type"].value_counts()

Unprovoked      3226
Provoked         374
Invalid          290
Boat             117
Sea Disaster      85
Boating           55
Name: Type, dtype: int64

In [51]:
def traducetipo(m, lexema="boat", resultado="Boating"):
    if lexema in str(m).lower():
        return resultado
    else:
        return m

In [52]:
data_clean2['Type'] = data_clean2['Type'].apply(traducetipo)
data_clean2["Type"].value_counts()

Unprovoked      3226
Provoked         374
Invalid          290
Boating          172
Sea Disaster      85
Name: Type, dtype: int64

In [53]:
data_clean3 = data_clean2.copy()[(data_clean2["Type"]=="Unprovoked")]
display(data_clean3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,5989
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,male,M,60s,Minor injury to arm,N,15h15,3' to 4' shark,5987
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,surfing,Fraser Penman,M,NaN,"No inury, board broken in half by shark",N,Late afternoon,NaN,5983
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,fishing and other types,Steve Cutbirth,M,NaN,Lacerations to face and right leg,N,NaN,"Bull shark, 6'",5966
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,female,F,9,Minor injury to leg,N,1300,NaN,5963
32,2016.07.15,15-Jul-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",swimming,male,M,NaN,Puncture wounds to foot,N,NaN,NaN,5961
33,2016.07.14.4,Reported 14-Jul-2016,2016,Unprovoked,BAHAMAS,NaN,Tiger Beach,diving,Michael Dornellas,M,NaN,Face bruised when partly blind shark collided ...,N,NaN,"Lemon shark, 9'",5960
34,2016.07.08.R,Reported 08-Jul-2016,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,NaN,Angel shark,5959
38,2016.07.06,06-Jul-16,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,14h30 / 15h30,NaN,5955
41,2016.06.25,25-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",surfing,male,M,11,Foot injured,N,14h34,NaN,5952
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Ryspunt,fishing and other types,male,M,43,Injuries to left leg & right hand,N,NaN,White shark,5950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,ND.0104,1950s,0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,NaN,"No injury, helmet bitten",N,NaN,Tiger shark,89
5906,ND.0100,2003?,0,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,fishing and other types,C.D. Dollar,M,NaN,Swim fin bitten,N,NaN,1.8 m [6'] shark,87
5907,ND.0097,No date,0,Unprovoked,USA,Florida,"Key West, Monroe County",surfing,Paul Menta,M,NaN,Hand bitten,N,NaN,NaN,86
5920,ND.0083,"No date, Before 1963",0,Unprovoked,USA,California,"LaJolla, San Diego County",diving,Charles Fleming,M,NaN,Calf bitten,N,NaN,"Shovelnose guitarfish, adult male",73
5923,ND.0078,"No date, Before 1902",0,Unprovoked,USA,Florida,"Mosquito Inlet (Ponce Inlet), Volusia County",canoeing,male,M,NaN,FATAL,Y,NaN,NaN,70
5925,ND.0075,"No date, Before 1963",0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,NaN,Calf removed,N,NaN,0.9 m [3'] shark,68
5926,ND.0074,"No date, After August 1926 and before 1936",0,Unprovoked,AUSTRALIA,Western Australia,Cossack Creek,diving,Ted Luck,M,NaN,Leg bitten,N,NaN,NaN,67
5928,ND.0069,Before 1962,0,Unprovoked,FIJI,NaN,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,65
5929,ND.0068,Before 1962,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,diving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",64
5937,ND.0058,Before 1958,0,Unprovoked,FIJI,Kadavu Island Group,"18.8S, 178.25E",fishing and other types,Fijian girl,F,NaN,"""Severely injured when fish were seized by shark""",N,NaN,NaN,56
5939,ND.0056,Before 1958,0,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",walk/stand/play & others,Horton Chase,M,NaN,Abrasions & bruises hip to ankle,N,NaN,NaN,54
5951,ND.0042,"""Before the war""",0,Unprovoked,AUSTRALIA,Torres Strait,Thursday Island?,diving,Mortakee,M,NaN,Head bitten,N,NaN,NaN,42
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,swimming,NaN,NaN,NaN,FATAL,Y,NaN,NaN,25
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,walk/stand/play & others,Madelaine Dalton,F,NaN,Ankle bitten,N,NaN,NaN,24
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,diving,Jaringoorli,M,NaN,Lacerations to thigh,N,NaN,NaN,23
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,Indian boy,M,NaN,"FATAL, leg severed",Y,NaN,NaN,22
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",fishing and other types,James Kelley,M,NaN,2-inch lacerations,N,NaN,NaN,20
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,male,M,NaN,FATAL,Y,NaN,NaN,18
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,bathing/floating,male,M,NaN,FATAL,Y,NaN,NaN,17
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,canoeing,20 Fijians,NaN,NaN,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN,16
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,swimming,"""youthful male""",M,NaN,"""Lost leg""",N,NaN,NaN,15
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,fishing and other types,a native fisherman,M,NaN,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN,14
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,walk/stand/play & others,a young Scotsman,M,NaN,"FATAL, leg stripped of flesh",Y,NaN,NaN,13
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,boy,M,NaN,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,10
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointer,9
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,NaN,FATAL,Y,NaN,Blue pointers,8
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,7
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,diving,male,M,NaN,FATAL,Y,NaN,NaN,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,4

In [54]:
data_clean3["Type"].value_counts()

Unprovoked    3226
Name: Type, dtype: int64

#### After cleaning activity, country and type, it was time to start with age. Ages were recorded as string types, so I needed to delete null values and convert them to 0 before changing the type to int in order to be able to make some calculations like the mean.

In [55]:
print(data_clean3["Age"].dtype)

object

In [56]:
data_clean3["Age"].fillna(0, inplace=True)
display(data_clean3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,0,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,0,No injury: Knocked off board by shark,N,NaN,2 m shark,5989
6,2016.09.11,11-Sep-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,male,M,60s,Minor injury to arm,N,15h15,3' to 4' shark,5987
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,surfing,Fraser Penman,M,0,"No inury, board broken in half by shark",N,Late afternoon,NaN,5983
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,fishing and other types,Steve Cutbirth,M,0,Lacerations to face and right leg,N,NaN,"Bull shark, 6'",5966
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,female,F,9,Minor injury to leg,N,1300,NaN,5963
32,2016.07.15,15-Jul-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",swimming,male,M,0,Puncture wounds to foot,N,NaN,NaN,5961
33,2016.07.14.4,Reported 14-Jul-2016,2016,Unprovoked,BAHAMAS,NaN,Tiger Beach,diving,Michael Dornellas,M,0,Face bruised when partly blind shark collided ...,N,NaN,"Lemon shark, 9'",5960
34,2016.07.08.R,Reported 08-Jul-2016,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,NaN,Angel shark,5959
38,2016.07.06,06-Jul-16,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,14h30 / 15h30,NaN,5955
41,2016.06.25,25-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",surfing,male,M,11,Foot injured,N,14h34,NaN,5952
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Ryspunt,fishing and other types,male,M,43,Injuries to left leg & right hand,N,NaN,White shark,5950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,ND.0104,1950s,0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,0,"No injury, helmet bitten",N,NaN,Tiger shark,89
5906,ND.0100,2003?,0,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,fishing and other types,C.D. Dollar,M,0,Swim fin bitten,N,NaN,1.8 m [6'] shark,87
5907,ND.0097,No date,0,Unprovoked,USA,Florida,"Key West, Monroe County",surfing,Paul Menta,M,0,Hand bitten,N,NaN,NaN,86
5920,ND.0083,"No date, Before 1963",0,Unprovoked,USA,California,"LaJolla, San Diego County",diving,Charles Fleming,M,0,Calf bitten,N,NaN,"Shovelnose guitarfish, adult male",73
5923,ND.0078,"No date, Before 1902",0,Unprovoked,USA,Florida,"Mosquito Inlet (Ponce Inlet), Volusia County",canoeing,male,M,0,FATAL,Y,NaN,NaN,70
5925,ND.0075,"No date, Before 1963",0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,0,Calf removed,N,NaN,0.9 m [3'] shark,68
5926,ND.0074,"No date, After August 1926 and before 1936",0,Unprovoked,AUSTRALIA,Western Australia,Cossack Creek,diving,Ted Luck,M,0,Leg bitten,N,NaN,NaN,67
5928,ND.0069,Before 1962,0,Unprovoked,FIJI,NaN,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,65
5929,ND.0068,Before 1962,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,diving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",64
5937,ND.0058,Before 1958,0,Unprovoked,FIJI,Kadavu Island Group,"18.8S, 178.25E",fishing and other types,Fijian girl,F,0,"""Severely injured when fish were seized by shark""",N,NaN,NaN,56
5939,ND.0056,Before 1958,0,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",walk/stand/play & others,Horton Chase,M,0,Abrasions & bruises hip to ankle,N,NaN,NaN,54
5951,ND.0042,"""Before the war""",0,Unprovoked,AUSTRALIA,Torres Strait,Thursday Island?,diving,Mortakee,M,0,Head bitten,N,NaN,NaN,42
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,swimming,NaN,NaN,0,FATAL,Y,NaN,NaN,25
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,walk/stand/play & others,Madelaine Dalton,F,0,Ankle bitten,N,NaN,NaN,24
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,diving,Jaringoorli,M,0,Lacerations to thigh,N,NaN,NaN,23
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,Indian boy,M,0,"FATAL, leg severed",Y,NaN,NaN,22
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",fishing and other types,James Kelley,M,0,2-inch lacerations,N,NaN,NaN,20
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,male,M,0,FATAL,Y,NaN,NaN,18
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,bathing/floating,male,M,0,FATAL,Y,NaN,NaN,17
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,canoeing,20 Fijians,NaN,0,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN,16
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,swimming,"""youthful male""",M,0,"""Lost leg""",N,NaN,NaN,15
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,fishing and other types,a native fisherman,M,0,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN,14
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,walk/stand/play & others,a young Scotsman,M,0,"FATAL, leg stripped of flesh",Y,NaN,NaN,13
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,boy,M,0,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,10
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,0,FATAL,Y,NaN,Blue pointer,9
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,0,FATAL,Y,NaN,Blue pointers,8
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,swimming,Arab boy,M,0,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,7
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,diving,male,M,0,FATAL,Y,NaN,NaN,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,diving,Ahmun,M,0,FATAL,Y,NaN,NaN,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,swimming,Coast Guard personnel,M,0,FATAL,Y,NaN,NaN,4

In [57]:
data_clean3["Age"].value_counts()

0           953
17          111
16          107
18          106
15          106
19           99
20           90
22           82
21           79
25           75
24           74
13           74
14           74
26           60
23           55
28           55
27           52
29           52
12           48
30           46
35           41
32           39
10           38
31           37
38           35
40           33
11           28
37           27
42           27
34           27
           ...
86            1
A.M.          1
3             1
87            1
Elderly       1
28 & 26       1
50s           1
33 or 37      1
74            1
65            1
30 or 36      1
84            1
25 or 28      1
31 or 33      1
77            1
18 to 22      1
40s           1
75            1
33 & 26       1
9 & 12        1
9 months      1
              1
73            1
20?           1
>50           1
young         1
"young"       1
12 or 13      1
X             1
(adult)       1
Name: Age, Length: 106, dtype: int64

In [58]:
data_clean4 = data_clean3.groupby("Age").filter(lambda x : len(x)>6)
display(data_clean4)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,0,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,0,No injury: Knocked off board by shark,N,NaN,2 m shark,5989
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
10,2016.09.05.a,05-Sep-16,2016,Unprovoked,AUSTRALIA,Western Australia,Injidup,surfing,Fraser Penman,M,0,"No inury, board broken in half by shark",N,Late afternoon,NaN,5983
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Green Turtle Cay,fishing and other types,Steve Cutbirth,M,0,Lacerations to face and right leg,N,NaN,"Bull shark, 6'",5966
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,female,F,9,Minor injury to leg,N,1300,NaN,5963
32,2016.07.15,15-Jul-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",swimming,male,M,0,Puncture wounds to foot,N,NaN,NaN,5961
33,2016.07.14.4,Reported 14-Jul-2016,2016,Unprovoked,BAHAMAS,NaN,Tiger Beach,diving,Michael Dornellas,M,0,Face bruised when partly blind shark collided ...,N,NaN,"Lemon shark, 9'",5960
34,2016.07.08.R,Reported 08-Jul-2016,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,NaN,Angel shark,5959
38,2016.07.06,06-Jul-16,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,14h30 / 15h30,NaN,5955
41,2016.06.25,25-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",surfing,male,M,11,Foot injured,N,14h34,NaN,5952
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Ryspunt,fishing and other types,male,M,43,Injuries to left leg & right hand,N,NaN,White shark,5950
44,2016.06.21.b,21-Jun-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",bathing/floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,15h25,3' to 5' shark,5949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5904,ND.0104,1950s,0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,0,"No injury, helmet bitten",N,NaN,Tiger shark,89
5906,ND.0100,2003?,0,Unprovoked,BAHAMAS,Andros Islands,Great Guana Cay,fishing and other types,C.D. Dollar,M,0,Swim fin bitten,N,NaN,1.8 m [6'] shark,87
5907,ND.0097,No date,0,Unprovoked,USA,Florida,"Key West, Monroe County",surfing,Paul Menta,M,0,Hand bitten,N,NaN,NaN,86
5920,ND.0083,"No date, Before 1963",0,Unprovoked,USA,California,"LaJolla, San Diego County",diving,Charles Fleming,M,0,Calf bitten,N,NaN,"Shovelnose guitarfish, adult male",73
5923,ND.0078,"No date, Before 1902",0,Unprovoked,USA,Florida,"Mosquito Inlet (Ponce Inlet), Volusia County",canoeing,male,M,0,FATAL,Y,NaN,NaN,70
5925,ND.0075,"No date, Before 1963",0,Unprovoked,AUSTRALIA,Torres Strait,NaN,diving,male,M,0,Calf removed,N,NaN,0.9 m [3'] shark,68
5926,ND.0074,"No date, After August 1926 and before 1936",0,Unprovoked,AUSTRALIA,Western Australia,Cossack Creek,diving,Ted Luck,M,0,Leg bitten,N,NaN,NaN,67
5928,ND.0069,Before 1962,0,Unprovoked,FIJI,NaN,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,65
5929,ND.0068,Before 1962,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,diving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",64
5937,ND.0058,Before 1958,0,Unprovoked,FIJI,Kadavu Island Group,"18.8S, 178.25E",fishing and other types,Fijian girl,F,0,"""Severely injured when fish were seized by shark""",N,NaN,NaN,56
5939,ND.0056,Before 1958,0,Unprovoked,USA,Florida,"Palm Beach, Palm Beach County",walk/stand/play & others,Horton Chase,M,0,Abrasions & bruises hip to ankle,N,NaN,NaN,54
5951,ND.0042,"""Before the war""",0,Unprovoked,AUSTRALIA,Torres Strait,Thursday Island?,diving,Mortakee,M,0,Head bitten,N,NaN,NaN,42
5968,ND.0024,Between 1918 & 1939,0,Unprovoked,REUNION,Saint-Denis,Barachois,swimming,NaN,NaN,0,FATAL,Y,NaN,NaN,25
5969,ND.0023,No date,0,Unprovoked,SOUTH AFRICA,Western Cape Province,Arniston,walk/stand/play & others,Madelaine Dalton,F,0,Ankle bitten,N,NaN,NaN,24
5970,ND.0022,No date,0,Unprovoked,AUSTRALIA,NaN,NaN,diving,Jaringoorli,M,0,Lacerations to thigh,N,NaN,NaN,23
5971,ND.0021,No date,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,Indian boy,M,0,"FATAL, leg severed",Y,NaN,NaN,22
5973,ND.0019,Before 1921,0,Unprovoked,USA,Florida,"Gadsden Point, Tampa Bay",fishing and other types,James Kelley,M,0,2-inch lacerations,N,NaN,NaN,20
5975,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,swimming,male,M,0,FATAL,Y,NaN,NaN,18
5976,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,bathing/floating,male,M,0,FATAL,Y,NaN,NaN,17
5977,ND.0015,Before 1917,0,Unprovoked,FIJI,Moala Island,NaN,canoeing,20 Fijians,NaN,0,"FATAL, 18 people were killed by sharks, 2 sur...",Y,NaN,NaN,16
5978,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,swimming,"""youthful male""",M,0,"""Lost leg""",N,NaN,NaN,15
5979,ND.0013,No date (3 days after preceding incident) & pr...,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,fishing and other types,a native fisherman,M,0,"FATAL, body not recovered but shark was caught...",Y,NaN,NaN,14
5980,ND.0012,Before 19-Jul-1913,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,walk/stand/play & others,a young Scotsman,M,0,"FATAL, leg stripped of flesh",Y,NaN,NaN,13
5983,ND.0009,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,boy,M,0,"FATAL, knocked overboard by tail of shark & ca...",Y,NaN,Blue pointer,10
5984,ND.0008,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,0,FATAL,Y,NaN,Blue pointer,9
5985,ND.0007,Before 1906,0,Unprovoked,AUSTRALIA,NaN,NaN,fishing and other types,fisherman,M,0,FATAL,Y,NaN,Blue pointers,8
5986,ND.0006,Before 1906,0,Unprovoked,AUSTRALIA,New South Wales,,swimming,Arab boy,M,0,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,7
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,diving,male,M,0,FATAL,Y,NaN,NaN,6
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,diving,Ahmun,M,0,FATAL,Y,NaN,NaN,5
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,swimming,Coast Guard personnel,M,0,FATAL,Y,NaN,NaN,4

In [59]:
data_clean4["Age"] = data_clean4["Age"].astype(int)
data_clean4.head()

/usr/local/Cellar/ipython/7.5.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,surfing,Rory Angiolella,M,0,Struck by fin on chest & leg,N,NaN,NaN,5990
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,surfing,male,M,0,No injury: Knocked off board by shark,N,NaN,2 m shark,5989

In [60]:
data_clean4.dtypes

Case Number       object
Date              object
Year               int64
Type              object
Country           object
Area              object
Location          object
Activity          object
Name              object
Sex               object
Age                int64
Injury            object
Fatal (Y/N)       object
Time              object
Species           object
original order     int64
dtype: object

In [61]:
data_clean5 = data_clean4.copy()[(data_clean4["Age"]>0)]
display(data_clean5)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,original order
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,5993
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,5992
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,5991
7,2016.09.07,07-Sep-16,2016,Unprovoked,USA,Hawaii,"Makaha, Oahu",swimming,female,F,51,Severe lacerations to shoulder & forearm,N,14h30,"Tiger shark, 10?",5986
8,2016.09.06,06-Sep-16,2016,Unprovoked,NEW CALEDONIA,North Province,Koumac,surfing,David Jewell,M,50,FATAL,Y,15h40,NaN,5985
9,2016.09.05.b,05-Sep-16,2016,Unprovoked,USA,South Carolina,"Kingston Plantation, Myrtle Beach, Horry County",other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,Late afternoon,NaN,5984
11,2016.09.04,04-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",other watersports,Austin Moore,M,9,Foot bitten,N,NaN,NaN,5982
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,"Refugio State Beach, Santa Barbara County",fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,NaN,White shark,5981
13,2016.08.29.b,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,15h00,"Bull shark, 6'",5980
14,2016.08.29.a,29-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,male,M,37,Minor injury to ankle,N,14h00,NaN,5979
15,2016.08.27,27-Aug-16,2016,Unprovoked,REUNION,NaN,Boucan Canot,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,17h00,"Bull shark, 3.5 m",5978
16,2016.08.25,25-Aug-16,2016,Unprovoked,USA,Florida,"Ponte Vedra, St. Johns County",walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,16h00,NaN,5977
17,2016.08.07,07-Aug-16,2016,Unprovoked,BAHAMAS,New Providence Island,Nassau,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,NaN,5976
18,2016.08.06,06-Aug-16,2016,Unprovoked,USA,Hawaii,Maui,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,NaN,"Tiger shark, 10'",5975
19,2016.08.04,04-Aug-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,Nolan Tyler,M,22,Big toe bitten,N,NaN,Blacktip shark,5974
20,2016.07.29,29-Jul-16,2016,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,swimming,male,M,40,Lacerations to right hand,N,11h30,Blue shark,5973
24,2016.07.26,26-Jul-16,2016,Unprovoked,AUSTRALIA,New South Wales,"Sharpes Beach, Ballina",surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,12h00,NaN,5969
26,2016.07.23.b,23-Jul-16,2016,Unprovoked,AUSTRALIA,Tasmania,Clifton Beach,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,NaN,5967
30,2016.07.16.b,16-Jul-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",surfing,female,F,9,Minor injury to leg,N,1300,NaN,5963
34,2016.07.08.R,Reported 08-Jul-2016,2016,Unprovoked,SPAIN,Canary Islands,"Las Teresitas, Tenerife",walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,NaN,Angel shark,5959
38,2016.07.06,06-Jul-16,2016,Unprovoked,USA,Florida,"Melbourne Beach, Brevard County",swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,14h30 / 15h30,NaN,5955
41,2016.06.25,25-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",surfing,male,M,11,Foot injured,N,14h34,NaN,5952
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Ryspunt,fishing and other types,male,M,43,Injuries to left leg & right hand,N,NaN,White shark,5950
44,2016.06.21.b,21-Jun-16,2016,Unprovoked,USA,South Carolina,"North Myrtle Beach, Horry County",bathing/floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,15h25,3' to 5' shark,5949
48,2016.06.14,14-Jun-16,2016,Unprovoked,USA,Texas,"Pirates Beach, Galveston",bathing/floating,Marin Alice Melton,F,6,Injury to lower leg,N,17h30,3' to 4' shark,5945
49,2016.06.11,11-Jun-16,2016,Unprovoked,USA,North Carolina,"Atlantic Beach, Emerald Isle, Carteret County",walk/stand/play & others,Dillon Bowen,M,19,Laceration to wrist,N,15h00,3' shark,5944
56,2016.05.31,31-May-16,2016,Unprovoked,AUSTRALIA,Western Australia,"Falcon Beach, Mandurah",surfing,Ben Gerring,M,29,FATAL,Y,16h00,White shark,5937
57,2016.05.29.b,29-May-16,2016,Unprovoked,USA,California,"Corona Del Mar, Newport, Orange County",swimming,Maria Korcsmaros \n,F,52,Injuries to arm and shoulder,N,16h00,NaN,5936
58,2016.05.29.a,29-May-16,2016,Unprovoked,USA,Florida,"Neptune, Duval County",swimming,male,M,13,Injury to posterior right leg,N,15h45,5' shark,5935
60,2016.05.21.b,21-May-16,2016,Unprovoked,USA,Florida,"St. Petersburg, Pinellas County",swimming,Krystal Magee,F,22,Lacerations and puncture wounds to foot and ankle,N,18h00,"Bull shark, 4' to 5'",5933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5382,1896.01.11,11-Jan-1896,1896,Unprovoked,AUSTRALIA,New South Wales,"Johnstone's Bay, Sydney",bathing/floating,William Ready,M,11,FATAL,Y,Afternoon,NaN,611
5385,1895.12.09,09-Dec-1895,1895,Unprovoked,AUSTRALIA,New South Wales,"West Balmain, Sydney",bathing/floating,Thomas John Terrill,M,14,FATAL,Y,NaN,NaN,608
5391,1895.08.11,11-Aug-1895,1895,Unprovoked,USA,Rhode Island,Noyes Beach,swimming,Charles Beattie,M,26,FATAL,Y,05h00,NaN,602
5401,1895.03.15,15-Mar-1895,1895,Unprovoked,AUSTRALIA,Queensland,Burnett River,swimming,Nicol Pringle,M,13,Lower leg & foot bitten,N,NaN,NaN,592
5402,1895.02.27,27-Feb-1895,1895,Unprovoked,AUSTRALIA,New South Wales,Sydney Harbor,swimming,James Edward Clifton Donald,M,14,FATAL,Y,NaN,NaN,591
5406,1894.11.28,28-Nov-1894,1894,Unprovoked,AUSTRALIA,New South Wales,Newcastle,bathing/floating,Horace Hewison,M,19,"""Lost his arm""",N,Morning,10' to 12' shark,587
5478,1888.12.09,09-Dec-1888,1888,Unprovoked,AUSTRALIA,New South Wales,"Iron Cove Bridge, Sydney (Estuary)",swimming,Stephen Carter,M,11,FATAL,Y,13h00,NaN,515
5502,1887.01.12,12-Jan-1887,1887,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Mzimvubu River, 9.6 km from the sea",swimming,Zangile,M,13,"FATAL, flesh removed hip to knee, calf & heel ...",Y,12h00,NaN,491
5507,1886.06.17,17-Jun-1886,1886,Unprovoked,AUSTRALIA,Queensland,Off Bribie Heads,swimming,Lacoon,M,18,FATAL,Y,NaN,NaN,486
5534,1883.12.19,19-Dec-1883,1883,Unprovoked,AUSTRALIA,New South Wales,Parramatta River,swimming,Cuthbert Vere Lysaght,M,21,FATAL,Y,12h00,NaN,459
5539,1883.01.21,21-Jan-1883,1883,Unprovoked,AUSTRALIA,New South Wales,"Iron Cove, Sydney",bathing/floating,John Eaton,M,37,FATAL,Y,05h30,NaN,454
5564,1880.11.25,25-Nov-1880,1880,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",swimming,Alexey Drury,M,12,"Feet bitten, surgically amputated FATAL",Y,Afternoon,Bull shark,429
5574,1880.01.03,03-Jan-1880,1880,Unprovoked,AUSTRALIA,New South Wales,Cooranbong,bathing/floating,Teresa Bonnell,F,13,Lacerations to leg,N,NaN,NaN,419
5584,1879.03.19,19-Mar-1879,1879,Unprovoked,NEW ZEALAND,North Island,Napier,walk/stand/play & others,Michal O'Neill,M,19,FATAL,Y,NaN,NaN,409
5594,1878.08.08,08-Aug-1878,1878,Unprovoked,USA,New York,Brooklyn,swimming,George Gates,M,14,FATAL,Y,Afternoon,NaN,399
5598,1878.00.00,1878,1878,Unprovoked,AUSTRALIA,New South Wales,"Balmain, Sydney (Estuary)",bathing/floating,boy,M,11,"FATAL, leg severed",Y,NaN,NaN,395
5600,1877.12.15,15-Dec-1877,1877,Unprovoked,AUSTRALIA,New South Wales,"Peacock Point, Balmain, Sydney",bathing/floating,Albert Thomas Burless,M,11,Leg severely bitten & later surgically amputated,N,NaN,NaN,393
5658,1870.05.26.R,Reported 26-May-1870,1870,Unprovoked,AUSTRALIA,Queensland,Moreton Island,fishing and other types,Master Lacy,M,13,bite to lower leg,N,NaN,NaN,335
5661,1870.01.09,09-Jan-1870,1870,Unprovoked,AUSTRALIA,Queensland,Brisbane River,bathing/floating,John Saunders,M,17,Right thigh bitten,N,NaN,NaN,332
5676,1865.09.02,02-Sep-1865,1865,Unprovoked,USA,New York,"Greenport Sound, Long Island",swimming,Peter Johnson,M,17,Multiple lacerations,N,09h00,NaN,317
5682,1864.08.12,12-Aug-1864,1864,Unprovoked,USA,New York,Mahattan,swimming,Henry Brice,M,13,Left thigh severely bitten,N,NaN,NaN,311
5693,1863.01.10,10-Jan-1863,1863,Unprovoked,AUSTRALIA,New South Wales,"""Bellynahinch"" on the Manning River",bathing/floating,James Brown,M,17,FATAL,Y,Evening,NaN,300
5695,1862.12.22,22-Dec-1862,1862,Unprovoked,NEW ZEALAND,North Island,"Soldier's Point, Brick Bay, Auckland",swimming,Thomas Cooke,M,28,Right thigh and left foot severely bitten,N,06h00 -- 07h00,NaN,298
5700,1862.07.25,25-Jul-1862,1862,Unprovoked,SPAIN,Malaga,San Andres Beach,swimming,Joaquin Rosales Martinez,M,18,FATAL,Y,NaN,NaN,293
5721,1858.03.14,14-Mar-1858,1858,Unprovoked,AUSTRALIA,Victoria,Hobson Bay,bathing/floating,Adolphe Bollander,M,22,FATAL,Y,15h00,NaN,272
5726,1856.02.06,06-Feb-1856,1856,Unprovoked,AUSTRALIA,Victoria,Point Henry,swimming,a seaman from the John and Lucy,M,17,Severe bite to thigh. Not known if he survived,UNKNOWN,NaN,NaN,267
5762,1848.08.31,31-Aug-1848,1848,Unprovoked,USA,Maryland,Patapsco River,swimming,male,M,15,Left leg severely bitten,N,NaN,NaN,231
5802,1830.07.26,26-Jul-1830,1830,Unprovoked,USA,Massachusetts,"Swampscott, Essex County",fishing and other types,Joseph Blaney,M,52,FATAL,Y,NaN,NaN,191
5928,ND.0069,Before 1962,0,Unprovoked,FIJI,NaN,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,NaN,1.8 m [6'] shark,65
5929,ND.0068,Before 1962,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,diving,Les Bishop,M,36,Bumped by sharks,N,NaN,"""A pack of sharks""",64

In [62]:
data_clean5.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'original order'],
      dtype='object')

#### After age, sex was next. Only a few values that were null or undefined. Only with the female and male values, I had over 2000 records, ¡still within the instructions limits! 💪🏼

In [63]:
data_clean5["Sex "].value_counts()

M      1882
F       266
lli       1
M         1
Name: Sex , dtype: int64

#### So, what other values were not going to be relevant for my analysis? Could I delete them in order to have the cleaniest data set? Here is the verification:

In [64]:
data_clean5.isnull().sum()

Case Number         0
Date                0
Year                0
Type                0
Country             0
Area               18
Location           37
Activity            0
Name                2
Sex                13
Age                 0
Injury              2
Fatal (Y/N)         0
Time              491
Species           799
original order      0
dtype: int64

#### Sex was deleted. Now, Time and Location were not relevant enough, and even deleting those values, my data set had over 2000 records... 💪🏼💪🏼

In [65]:
rows_to_delete = data_clean5[(data_clean5["Sex "].isnull())]
rows_to_delete.shape

(13, 16)

In [66]:
data_clean6 = data_clean5.drop(rows_to_delete.index, axis=0)
display(data_clean5.shape)
display(data_clean6.shape)

(2163, 16)

(2150, 16)

In [67]:
data_clean6.isnull().sum()

Case Number         0
Date                0
Year                0
Type                0
Country             0
Area               17
Location           36
Activity            0
Name                2
Sex                 0
Age                 0
Injury              2
Fatal (Y/N)         0
Time              482
Species           788
original order      0
dtype: int64

In [68]:
data_clean7 = data_clean6.drop(columns=['Date', 'Time', 'Location']).copy()
data_clean7

,Case Number,Year,Type,Country,Area,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Species,original order
0,2016.09.18.c,2016,Unprovoked,USA,Florida,surfing,male,M,16,Minor injury to thigh,N,NaN,5993
1,2016.09.18.b,2016,Unprovoked,USA,Florida,surfing,Chucky Luciano,M,36,Lacerations to hands,N,NaN,5992
2,2016.09.18.a,2016,Unprovoked,USA,Florida,surfing,male,M,43,Lacerations to lower leg,N,NaN,5991
7,2016.09.07,2016,Unprovoked,USA,Hawaii,swimming,female,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",5986
8,2016.09.06,2016,Unprovoked,NEW CALEDONIA,North Province,surfing,David Jewell,M,50,FATAL,Y,NaN,5985
9,2016.09.05.b,2016,Unprovoked,USA,South Carolina,other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,NaN,5984
11,2016.09.04,2016,Unprovoked,USA,Florida,other watersports,Austin Moore,M,9,Foot bitten,N,NaN,5982
12,2016.09.01,2016,Unprovoked,USA,California,fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,White shark,5981
13,2016.08.29.b,2016,Unprovoked,USA,Florida,surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,"Bull shark, 6'",5980
14,2016.08.29.a,2016,Unprovoked,USA,Florida,surfing,male,M,37,Minor injury to ankle,N,NaN,5979
15,2016.08.27,2016,Unprovoked,REUNION,NaN,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,"Bull shark, 3.5 m",5978
16,2016.08.25,2016,Unprovoked,USA,Florida,walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,NaN,5977
17,2016.08.07,2016,Unprovoked,BAHAMAS,New Providence Island,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,5976
18,2016.08.06,2016,Unprovoked,USA,Hawaii,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,"Tiger shark, 10'",5975
19,2016.08.04,2016,Unprovoked,USA,Florida,surfing,Nolan Tyler,M,22,Big toe bitten,N,Blacktip shark,5974
20,2016.07.29,2016,Unprovoked,SPAIN,Alicante Province,swimming,male,M,40,Lacerations to right hand,N,Blue shark,5973
24,2016.07.26,2016,Unprovoked,AUSTRALIA,New South Wales,surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,NaN,5969
26,2016.07.23.b,2016,Unprovoked,AUSTRALIA,Tasmania,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,5967
30,2016.07.16.b,2016,Unprovoked,USA,Florida,surfing,female,F,9,Minor injury to leg,N,NaN,5963
34,2016.07.08.R,2016,Unprovoked,SPAIN,Canary Islands,walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,Angel shark,5959
38,2016.07.06,2016,Unprovoked,USA,Florida,swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,NaN,5955
41,2016.06.25,2016,Unprovoked,USA,North Carolina,surfing,male,M,11,Foot injured,N,NaN,5952
43,2016.06.23,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,fishing and other types,male,M,43,Injuries to left leg & right hand,N,White shark,5950
44,2016.06.21.b,2016,Unprovoked,USA,South Carolina,bathing/floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,3' to 5' shark,5949
48,2016.06.14,2016,Unprovoked,USA,Texas,bathing/floating,Marin Alice Melton,F,6,Injury to lower leg,N,3' to 4' shark,5945
49,2016.06.11,2016,Unprovoked,USA,North Carolina,walk/stand/play & others,Dillon Bowen,M,19,Laceration to wrist,N,3' shark,5944
56,2016.05.31,2016,Unprovoked,AUSTRALIA,Western Australia,surfing,Ben Gerring,M,29,FATAL,Y,White shark,5937
57,2016.05.29.b,2016,Unprovoked,USA,California,swimming,Maria Korcsmaros \n,F,52,Injuries to arm and shoulder,N,NaN,5936
58,2016.05.29.a,2016,Unprovoked,USA,Florida,swimming,male,M,13,Injury to posterior right leg,N,5' shark,5935
60,2016.05.21.b,2016,Unprovoked,USA,Florida,swimming,Krystal Magee,F,22,Lacerations and puncture wounds to foot and ankle,N,"Bull shark, 4' to 5'",5933
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5382,1896.01.11,1896,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,William Ready,M,11,FATAL,Y,NaN,611
5385,1895.12.09,1895,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Thomas John Terrill,M,14,FATAL,Y,NaN,608
5391,1895.08.11,1895,Unprovoked,USA,Rhode Island,swimming,Charles Beattie,M,26,FATAL,Y,NaN,602
5401,1895.03.15,1895,Unprovoked,AUSTRALIA,Queensland,swimming,Nicol Pringle,M,13,Lower leg & foot bitten,N,NaN,592
5402,1895.02.27,1895,Unprovoked,AUSTRALIA,New South Wales,swimming,James Edward Clifton Donald,M,14,FATAL,Y,NaN,591
5406,1894.11.28,1894,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Horace Hewison,M,19,"""Lost his arm""",N,10' to 12' shark,587
5478,1888.12.09,1888,Unprovoked,AUSTRALIA,New South Wales,swimming,Stephen Carter,M,11,FATAL,Y,NaN,515
5502,1887.01.12,1887,Unprovoked,SOUTH AFRICA,Eastern Cape Province,swimming,Zangile,M,13,"FATAL, flesh removed hip to knee, calf & heel ...",Y,NaN,491
5507,1886.06.17,1886,Unprovoked,AUSTRALIA,Queensland,swimming,Lacoon,M,18,FATAL,Y,NaN,486
5534,1883.12.19,1883,Unprovoked,AUSTRALIA,New South Wales,swimming,Cuthbert Vere Lysaght,M,21,FATAL,Y,NaN,459
5539,1883.01.21,1883,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,John Eaton,M,37,FATAL,Y,NaN,454
5564,1880.11.25,1880,Unprovoked,AUSTRALIA,Queensland,swimming,Alexey Drury,M,12,"Feet bitten, surgically amputated FATAL",Y,Bull shark,429
5574,1880.01.03,1880,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Teresa Bonnell,F,13,Lacerations to leg,N,NaN,419
5584,1879.03.19,1879,Unprovoked,NEW ZEALAND,North Island,walk/stand/play & others,Michal O'Neill,M,19,FATAL,Y,NaN,409
5594,1878.08.08,1878,Unprovoked,USA,New York,swimming,George Gates,M,14,FATAL,Y,NaN,399
5598,1878.00.00,1878,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,boy,M,11,"FATAL, leg severed",Y,NaN,395
5600,1877.12.15,1877,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Albert Thomas Burless,M,11,Leg severely bitten & later surgically amputated,N,NaN,393
5658,1870.05.26.R,1870,Unprovoked,AUSTRALIA,Queensland,fishing and other types,Master Lacy,M,13,bite to lower leg,N,NaN,335
5661,1870.01.09,1870,Unprovoked,AUSTRALIA,Queensland,bathing/floating,John Saunders,M,17,Right thigh bitten,N,NaN,332
5676,1865.09.02,1865,Unprovoked,USA,New York,swimming,Peter Johnson,M,17,Multiple lacerations,N,NaN,317
5682,1864.08.12,1864,Unprovoked,USA,New York,swimming,Henry Brice,M,13,Left thigh severely bitten,N,NaN,311
5693,1863.01.10,1863,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,James Brown,M,17,FATAL,Y,NaN,300
5695,1862.12.22,1862,Unprovoked,NEW ZEALAND,North Island,swimming,Thomas Cooke,M,28,Right thigh and left foot severely bitten,N,NaN,298
5700,1862.07.25,1862,Unprovoked,SPAIN,Malaga,swimming,Joaquin Rosales Martinez,M,18,FATAL,Y,NaN,293
5721,1858.03.14,1858,Unprovoked,AUSTRALIA,Victoria,bathing/floating,Adolphe Bollander,M,22,FATAL,Y,NaN,272
5726,1856.02.06,1856,Unprovoked,AUSTRALIA,Victoria,swimming,a seaman from the John and Lucy,M,17,Severe bite to thigh. Not known if he survived,UNKNOWN,NaN,267
5762,1848.08.31,1848,Unprovoked,USA,Maryland,swimming,male,M,15,Left leg severely bitten,N,NaN,231
5802,1830.07.26,1830,Unprovoked,USA,Massachusetts,fishing and other types,Joseph Blaney,M,52,FATAL,Y,NaN,191
5928,ND.0069,0,Unprovoked,FIJI,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,1.8 m [6'] shark,65
5929,ND.0068,0,Unprovoked,MOZAMBIQUE,Maputo Province,diving,Les Bishop,M,36,Bumped by sharks,N,"""A pack of sharks""",64

In [69]:
data_clean7.isnull().sum()

Case Number         0
Year                0
Type                0
Country             0
Area               17
Activity            0
Name                2
Sex                 0
Age                 0
Injury              2
Fatal (Y/N)         0
Species           788
original order      0
dtype: int64

In [70]:
data_clean7.shape

(2150, 13)

#### Now I had the last and ultimate data set. I needed to rename the columns in order for it the be "prettier" but also, I needed to rename the data set to start the analysis with that last set clean and pretty.

In [71]:
data_last = data_clean7.copy()
columns=["CASE NUMBER", "YEAR", "TYPE", "COUNTRY", "AREA", "ACTIVITY", "NAME", "SEX", "AGE", "INJURY", "FATAL", "SPECIES", "ORIGINAL ORDER"]
data_last.columns = columns
display(data_last)

,CASE NUMBER,YEAR,TYPE,COUNTRY,AREA,ACTIVITY,NAME,SEX,AGE,INJURY,FATAL,SPECIES,ORIGINAL ORDER
0,2016.09.18.c,2016,Unprovoked,USA,Florida,surfing,male,M,16,Minor injury to thigh,N,NaN,5993
1,2016.09.18.b,2016,Unprovoked,USA,Florida,surfing,Chucky Luciano,M,36,Lacerations to hands,N,NaN,5992
2,2016.09.18.a,2016,Unprovoked,USA,Florida,surfing,male,M,43,Lacerations to lower leg,N,NaN,5991
7,2016.09.07,2016,Unprovoked,USA,Hawaii,swimming,female,F,51,Severe lacerations to shoulder & forearm,N,"Tiger shark, 10?",5986
8,2016.09.06,2016,Unprovoked,NEW CALEDONIA,North Province,surfing,David Jewell,M,50,FATAL,Y,NaN,5985
9,2016.09.05.b,2016,Unprovoked,USA,South Carolina,other watersports,Rylie Williams,F,12,Lacerations & punctures to lower right leg,N,NaN,5984
11,2016.09.04,2016,Unprovoked,USA,Florida,other watersports,Austin Moore,M,9,Foot bitten,N,NaN,5982
12,2016.09.01,2016,Unprovoked,USA,California,fishing and other types,Tyler McQuillen,M,22,Two toes broken & lacerated,N,White shark,5981
13,2016.08.29.b,2016,Unprovoked,USA,Florida,surfing,Sam Cumiskey,M,25,Lacerations to right foot,N,"Bull shark, 6'",5980
14,2016.08.29.a,2016,Unprovoked,USA,Florida,surfing,male,M,37,Minor injury to ankle,N,NaN,5979
15,2016.08.27,2016,Unprovoked,REUNION,NaN,surfing,Laurent Chardard,M,20,"Right arm severed, ankle severely bitten",N,"Bull shark, 3.5 m",5978
16,2016.08.25,2016,Unprovoked,USA,Florida,walk/stand/play & others,David Cassetty,M,49,Minor injury to ankle,N,NaN,5977
17,2016.08.07,2016,Unprovoked,BAHAMAS,New Providence Island,snorkeling,Johnny Stoch,M,15,Lacerations to left leg,N,NaN,5976
18,2016.08.06,2016,Unprovoked,USA,Hawaii,other watersports,Connor Baxter,M,21,"No inury, shark & board collided",N,"Tiger shark, 10'",5975
19,2016.08.04,2016,Unprovoked,USA,Florida,surfing,Nolan Tyler,M,22,Big toe bitten,N,Blacktip shark,5974
20,2016.07.29,2016,Unprovoked,SPAIN,Alicante Province,swimming,male,M,40,Lacerations to right hand,N,Blue shark,5973
24,2016.07.26,2016,Unprovoked,AUSTRALIA,New South Wales,surfing,Curran See & Harry Lake,M,18,"No injury. Leg rope severed, knocked off board...",N,NaN,5969
26,2016.07.23.b,2016,Unprovoked,AUSTRALIA,Tasmania,surfing,Zebulon Critchlow,M,36,Calf bumped but no injury,N,NaN,5967
30,2016.07.16.b,2016,Unprovoked,USA,Florida,surfing,female,F,9,Minor injury to leg,N,NaN,5963
34,2016.07.08.R,2016,Unprovoked,SPAIN,Canary Islands,walk/stand/play & others,female,F,10,"5 tiny puncture marks to lower leg, treated wi...",N,Angel shark,5959
38,2016.07.06,2016,Unprovoked,USA,Florida,swimming,female,F,42,"Buttocks, thigh, left hand & wrist injured",N,NaN,5955
41,2016.06.25,2016,Unprovoked,USA,North Carolina,surfing,male,M,11,Foot injured,N,NaN,5952
43,2016.06.23,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,fishing and other types,male,M,43,Injuries to left leg & right hand,N,White shark,5950
44,2016.06.21.b,2016,Unprovoked,USA,South Carolina,bathing/floating,Jeff Schott,M,42,Lacerations and punctures to foot,N,3' to 5' shark,5949
48,2016.06.14,2016,Unprovoked,USA,Texas,bathing/floating,Marin Alice Melton,F,6,Injury to lower leg,N,3' to 4' shark,5945
49,2016.06.11,2016,Unprovoked,USA,North Carolina,walk/stand/play & others,Dillon Bowen,M,19,Laceration to wrist,N,3' shark,5944
56,2016.05.31,2016,Unprovoked,AUSTRALIA,Western Australia,surfing,Ben Gerring,M,29,FATAL,Y,White shark,5937
57,2016.05.29.b,2016,Unprovoked,USA,California,swimming,Maria Korcsmaros \n,F,52,Injuries to arm and shoulder,N,NaN,5936
58,2016.05.29.a,2016,Unprovoked,USA,Florida,swimming,male,M,13,Injury to posterior right leg,N,5' shark,5935
60,2016.05.21.b,2016,Unprovoked,USA,Florida,swimming,Krystal Magee,F,22,Lacerations and puncture wounds to foot and ankle,N,"Bull shark, 4' to 5'",5933
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5382,1896.01.11,1896,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,William Ready,M,11,FATAL,Y,NaN,611
5385,1895.12.09,1895,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Thomas John Terrill,M,14,FATAL,Y,NaN,608
5391,1895.08.11,1895,Unprovoked,USA,Rhode Island,swimming,Charles Beattie,M,26,FATAL,Y,NaN,602
5401,1895.03.15,1895,Unprovoked,AUSTRALIA,Queensland,swimming,Nicol Pringle,M,13,Lower leg & foot bitten,N,NaN,592
5402,1895.02.27,1895,Unprovoked,AUSTRALIA,New South Wales,swimming,James Edward Clifton Donald,M,14,FATAL,Y,NaN,591
5406,1894.11.28,1894,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Horace Hewison,M,19,"""Lost his arm""",N,10' to 12' shark,587
5478,1888.12.09,1888,Unprovoked,AUSTRALIA,New South Wales,swimming,Stephen Carter,M,11,FATAL,Y,NaN,515
5502,1887.01.12,1887,Unprovoked,SOUTH AFRICA,Eastern Cape Province,swimming,Zangile,M,13,"FATAL, flesh removed hip to knee, calf & heel ...",Y,NaN,491
5507,1886.06.17,1886,Unprovoked,AUSTRALIA,Queensland,swimming,Lacoon,M,18,FATAL,Y,NaN,486
5534,1883.12.19,1883,Unprovoked,AUSTRALIA,New South Wales,swimming,Cuthbert Vere Lysaght,M,21,FATAL,Y,NaN,459
5539,1883.01.21,1883,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,John Eaton,M,37,FATAL,Y,NaN,454
5564,1880.11.25,1880,Unprovoked,AUSTRALIA,Queensland,swimming,Alexey Drury,M,12,"Feet bitten, surgically amputated FATAL",Y,Bull shark,429
5574,1880.01.03,1880,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Teresa Bonnell,F,13,Lacerations to leg,N,NaN,419
5584,1879.03.19,1879,Unprovoked,NEW ZEALAND,North Island,walk/stand/play & others,Michal O'Neill,M,19,FATAL,Y,NaN,409
5594,1878.08.08,1878,Unprovoked,USA,New York,swimming,George Gates,M,14,FATAL,Y,NaN,399
5598,1878.00.00,1878,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,boy,M,11,"FATAL, leg severed",Y,NaN,395
5600,1877.12.15,1877,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,Albert Thomas Burless,M,11,Leg severely bitten & later surgically amputated,N,NaN,393
5658,1870.05.26.R,1870,Unprovoked,AUSTRALIA,Queensland,fishing and other types,Master Lacy,M,13,bite to lower leg,N,NaN,335
5661,1870.01.09,1870,Unprovoked,AUSTRALIA,Queensland,bathing/floating,John Saunders,M,17,Right thigh bitten,N,NaN,332
5676,1865.09.02,1865,Unprovoked,USA,New York,swimming,Peter Johnson,M,17,Multiple lacerations,N,NaN,317
5682,1864.08.12,1864,Unprovoked,USA,New York,swimming,Henry Brice,M,13,Left thigh severely bitten,N,NaN,311
5693,1863.01.10,1863,Unprovoked,AUSTRALIA,New South Wales,bathing/floating,James Brown,M,17,FATAL,Y,NaN,300
5695,1862.12.22,1862,Unprovoked,NEW ZEALAND,North Island,swimming,Thomas Cooke,M,28,Right thigh and left foot severely bitten,N,NaN,298
5700,1862.07.25,1862,Unprovoked,SPAIN,Malaga,swimming,Joaquin Rosales Martinez,M,18,FATAL,Y,NaN,293
5721,1858.03.14,1858,Unprovoked,AUSTRALIA,Victoria,bathing/floating,Adolphe Bollander,M,22,FATAL,Y,NaN,272
5726,1856.02.06,1856,Unprovoked,AUSTRALIA,Victoria,swimming,a seaman from the John and Lucy,M,17,Severe bite to thigh. Not known if he survived,UNKNOWN,NaN,267
5762,1848.08.31,1848,Unprovoked,USA,Maryland,swimming,male,M,15,Left leg severely bitten,N,NaN,231
5802,1830.07.26,1830,Unprovoked,USA,Massachusetts,fishing and other types,Joseph Blaney,M,52,FATAL,Y,NaN,191
5928,ND.0069,0,Unprovoked,FIJI,NaN,fishing and other types,Dalton Baldwin,M,27,"No injury, bumped by shark which took speared ...",N,1.8 m [6'] shark,65
5929,ND.0068,0,Unprovoked,MOZAMBIQUE,Maputo Province,diving,Les Bishop,M,36,Bumped by sharks,N,"""A pack of sharks""",64

## Time to analyze 🤓

In [72]:
new_df = pd.DataFrame()
new_df['TOTAL'] = data_last[data_last['SEX']!=None].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX']
new_df['MALE %'] = (data_last[data_last['SEX']=="M"].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX'])*100/new_df['TOTAL']
new_df['FEMALE %'] = (data_last[data_last['SEX']=="F"].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX'])*100/new_df['TOTAL']
new_df['AVG AGE MALE'] = (data_last[(data_last['AGE']!=None)&(data_last['SEX']=="M")].groupby(['COUNTRY', 'ACTIVITY']).mean()['AGE'])
new_df['AVG AGE FEMALE'] = (data_last[(data_last['AGE']!=None)&(data_last['SEX']=="F")].groupby(['COUNTRY', 'ACTIVITY']).mean()['AGE'])
new_df['TOTAL FATALS'] = data_last[(data_last['FATAL']=="Y")].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX']
new_df['% FATALS MALE'] = data_last[(data_last['FATAL']=="Y")&(data_last['SEX']=="M")].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX']*100/new_df['TOTAL FATALS']
new_df['% FATALS FEMALE'] = data_last[(data_last['FATAL']=="Y")&(data_last['SEX']=="F")].groupby(['COUNTRY', 'ACTIVITY']).count()['SEX']*100/new_df['TOTAL FATALS']
new_df['AVG AGE MALE FATALS'] = (data_last[(data_last['AGE']!=None)&(data_last['SEX']=="M")&(data_last['FATAL']=="Y")].groupby(['COUNTRY', 'ACTIVITY']).mean()['AGE'])
new_df['AVG AGE FEMALE FATALS'] = (data_last[(data_last['AGE']!=None)&(data_last['SEX']=="F")&(data_last['FATAL']=="Y")].groupby(['COUNTRY', 'ACTIVITY']).mean()['AGE'])
new_df.round(decimals=2).fillna(0)

                                           TOTAL  MALE %  FEMALE %  \
COUNTRY          ACTIVITY
AUSTRALIA        bathing/floating             37   89.19     10.81
                 diving                       65   96.92      3.08
                 fishing and other types      63  100.00      0.00
                 helping sharks                1  100.00      0.00
                 kayaking                      5  100.00      0.00
                 other watersports            15  100.00      0.00
                 snorkeling                   12   58.33     41.67
                 surfing                     154   95.45      4.55
                 swimming                    108   90.74      9.26
                 walk/stand/play & others     24   66.67     33.33
BAHAMAS          bathing/floating              1  100.00      0.00
                 diving                        8   87.50     12.50
                 fishing and other types      30   83.33     16.67
                 snorkeling                    4   50.00     50.00
                 surfing                       1  100.00      0.00
                 swimming                      2  100.00      0.00
                 walk/stand/play & others      1  100.00      0.00
BRAZIL           bathing/floating              1  100.00      0.00
                 diving                        1  100.00      0.00
                 fishing and other types       3  100.00      0.00
                 other watersports             3  100.00      0.00
                 surfing                      19  100.00      0.00
                 swimming                     18   94.44      5.56
                 walk/stand/play & others      1    0.00    100.00
FIJI             diving                        5  100.00      0.00
                 fishing and other types      11   90.91      9.09
                 snorkeling                    1    0.00    100.00
                 surfing                       1  100.00      0.00
                 swimming                      3   66.67     33.33
ITALY            fishing and other types       4  100.00      0.00
...                                          ...     ...       ...
PAPUA NEW GUINEA walk/stand/play & others      3  100.00      0.00
PHILIPPINES      bathing/floating              1  100.00      0.00
                 fishing and other types       1  100.00      0.00
                 surfing                       1  100.00      0.00
                 swimming                      4  100.00      0.00
REUNION          fishing and other types       2  100.00      0.00
                 other watersports             9  100.00      0.00
                 surfing                      17  100.00      0.00
                 swimming                      3   33.33     66.67
SOUTH AFRICA     bathing/floating             20   95.00      5.00
                 diving                        8  100.00      0.00
                 fishing and other types      44  100.00      0.00
                 other watersports            18  100.00      0.00
                 snorkeling                    2   50.00     50.00
                 surfing                     106   98.11      1.89
                 swimming                     65   95.38      4.62
                 walk/stand/play & others     21   90.48      9.52
                 war/battle                    1  100.00      0.00
SPAIN            swimming                      4   75.00     25.00
                 walk/stand/play & others      2   50.00     50.00
USA              bathing/floating             25   72.00     28.00
                 diving                       51   98.04      1.96
                 fishing and other types      81   92.59      7.41
                 helping sharks                1  100.00      0.00
                 kayaking                      4   50.00     50.00
                 other watersports            61   73.77     26.23
                 snorkeling                   16   62.50     37.50
                 surfing                     489   93.66      6.13
                 swimming                    207   71.50     28.02
                 walk/stand/play & others    147   57.82     42.18

                                           AVG AGE MALE  AVG AGE FEMALE  \
COUNTRY          ACTIVITY
AUSTRALIA        bathing/floating                 20.91           25.75
                 diving                           29.32           33.50
                 fishing and other types          26.78            0.00
                 helping sharks                   20.00            0.00
                 kayaking                         28.60            0.00
                 other watersports                20.07            0.00
                 snorkeling                       33.43           14.80
                 surfing                          27.31           24.57
                 swimming                         22.36           21.80
                 walk/stand/play & others         24.62           24.62
BAHAMAS          bathing/floating                 32.00            0.00
                 diving                           43.14           26.00
                 fishing and other types          33.60           36.80
                 snorkeling                       25.00           26.00
                 surfing                          53.00            0.00
                 swimming                         42.00            0.00
                 walk/stand/play & others         43.00            0.00
BRAZIL           bathing/floating                 24.00            0.00
                 diving                           32.00            0.00
                 fishing and other types          36.67            0.00
                 other watersports                21.33            0.00
                 surfing                          21.95            0.00
                 swimming                         21.53           18.00
                 walk/stand/play & others          0.00           24.00
FIJI             diving                           29.00            0.00
                 fishing and other types          27.10           21.00
                 snorkeling                        0.00           47.00
                 surfing                          21.00            0.00
                 swimming                         38.50           20.00
ITALY            fishing and other types          26.00            0.00
...                                                 ...             ...
PAPUA NEW GUINEA walk/stand/play & others         17.67            0.00
PHILIPPINES      bathing/floating                 21.00            0.00
                 fishing and other types          39.00            0.00
                 surfing                          58.00            0.00
                 swimming                         22.75            0.00
REUNION          fishing and other types          32.00            0.00
                 other watersports                26.11            0.00
                 surfing                          29.12            0.00
                 swimming                         52.00           18.50
SOUTH AFRICA     bathing/floating                 20.42           18.00
                 diving                           32.12            0.00
                 fishing and other types          29.09            0.00
                 other watersports                21.00            0.00
                 snorkeling                       25.00           21.00
                 surfing                          24.49           18.00
                 swimming                         22.61           18.67
                 walk/stand/play & others         21.32           17.00
                 war/battle                       35.00            0.00
SPAIN            swimming                         32.00           38.00
                 walk/stand/play & others         16.00           10.00
USA              bathing/floating                 25.39           16.86
                 diving                           31.26           22.00
                 fishing and other types          27.83           38.83
                 helping sharks                    9.00            0.00
                 kayaking                         50.50           32.00
                 other watersports                20.82           12.88
                 snorkeling                       34.80           42.33
                 surfing                          25.45           23.97
                 swimming                         24.64           23.36
                 walk/stand/play & others         19.29           20.84

                                           TOTAL FATALS  % FATALS MALE  \
COUNTRY          ACTIVITY
AUSTRALIA        bathing/floating                  20.0          95.00
                 diving                            27.0          92.59
                 fishing and other types           13.0         100.00
                 helping sharks                     0.0           0.00
                 kayaking                           0.0           0.00
                 other watersports                  3.0         100.00
                 snorkeling                         2.0         100.00
                 surfing                           23.0         100.00
                 swimming                          50.0          94.00
                 walk/stand/play & others           9.0          66.67
BAHAMAS          bathing/floating                   0.0           0.00
                 diving                             1.0         100.00
                 fishing and other types            1.0         100.00
                 snorkeling                         0.0           0.00
                 surfing                            0.0           0.00
                 swimming                           0.0           0.00
                 walk/stand/play & others           0.0           0.00
BRAZIL           bathing/floating                   0.0           0.00
                 diving                             0.0           0.00
                 fishing and other types            0.0           0.00
                 other watersports                  1.0         100.00
                 surfing                            3.0         100.00
                 swimming                          11.0          90.91
                 walk/stand/play & others           0.0           0.00
FIJI             diving                             2.0         100.00
                 fishing and other types            2.0         100.00
                 snorkeling                         0.0           0.00
                 surfing                            0.0           0.00
                 swimming                           1.0         100.00
ITALY            fishing and other types            1.0         100.00
...                                                 ...            ...
PAPUA NEW GUINEA walk/stand/play & others           0.0           0.00
PHILIPPINES      bathing/floating                   0.0           0.00
                 fishing and other types            1.0         100.00
                 surfing                            1.0         100.00
                 swimming                           2.0         100.00
REUNION          fishing and other types            0.0           0.00
                 other watersports                  3.0         100.00
                 surfing                            6.0         100.00
                 swimming                           3.0          33.33
SOUTH AFRICA     bathing/floating                   4.0         100.00
                 diving                             1.0         100.00
                 fishing and other types            6.0         100.00
                 other watersports                  5.0         100.00
                 snorkeling                         0.0           0.00
                 surfing                           13.0          92.31
                 swimming                          29.0         100.00
                 walk/stand/play & others           4.0         100.00
                 war/battle                         0.0           0.00
SPAIN            swimming                           1.0         100.00
                 walk/stand/play & others           0.0           0.00
USA              bathing/floating                   3.0          66.67
                 diving                             8.0         100.00
                 fishing and other types            7.0         100.00
                 helping sharks                     0.0           0.00
                 kayaking                           1.0           0.00
                 other watersports                  3.0         100.00
                 snorkeling                         3.0          33.33
                 surfing                            5.0         100.00
                 swimming                          27.0          85.19
                 walk/stand/play & others           2.0         100.00

                                           % FATALS FEMALE  \
COUNTRY          ACTIVITY
AUSTRALIA        bathing/floating                     5.00
                 diving                               7.41
                 fishing and other types              0.00
                 helping sharks                       0.00
                 kayaking                             0.00
                 other watersports                    0.00
                 snorkeling                           0.00
                 surfing                              0.00
                 swimming                             6.00
                 walk/stand/play & others            33.33
BAHAMAS          bathing/floating                     0.00
                 diving                               0.00
                 fishing and other types              0.00
                 snorkeling                           0.00
                 surfing                              0.00
                 swimming                             0.00
                 walk/stand/play & others             0.00
BRAZIL           bathing/floating                     0.00
                 diving                               0.00
                 fishing and other types              0.00
                 other watersports                    0.00
                 surfing                              0.00
                 swimming                             9.09
                 walk/stand/play & others             0.00
FIJI             diving                               0.00
                 fishing and other types              0.00
                 snorkeling                           0.00
                 surfing                              0.00
                 swimming                             0.00
ITALY            fishing and other types              0.00
...                                                    ...
PAPUA NEW GUINEA walk/stand/play & others             0.00
PHILIPPINES      bathing/floating                     0.00
                 fishing and other types              0.00
                 surfing                              0.00
                 swimming                             0.00
REUNION          fishing and other types              0.00
                 other watersports                    0.00
                 surfing                              0.00
                 swimming                            66.67
SOUTH AFRICA     bathing/floating                     0.00
                 diving                               0.00
                 fishing and other types              0.00
                 other watersports                    0.00
                 snorkeling                           0.00
                 surfing                              7.69
                 swimming                             0.00
                 walk/stand/play & others             0.00
                 war/battle                           0.00
SPAIN            swimming                             0.00
                 walk/stand/play & others             0.00
USA              bathing/floating                    33.33
                 diving                               0.00
                 fishing and other types              0.00
                 helping sharks                       0.00
                 kayaking                           100.00
                 other watersports                    0.00
                 snorkeling                          66.67
                 surfing                              0.00
                 swimming                            14.81
                 walk/stand/play & others             0.00

                                           AVG AGE MALE FATALS  \
COUNTRY          ACTIVITY
AUSTRALIA        bathing/floating                        23.21
                 diving                                  27.12
                 fishing and other types                 24.69
                 helping sharks                           0.00
                 kayaking                                 0.00
                 other watersports                       18.67
                 snorkeling                              38.50
                 surfing                                 24.96
                 swimming                                23.04
                 walk/stand/play & others                29.83
BAHAMAS          bathing/floating                         0.00
                 diving                                  49.00
                 fishing and other types                 15.00
                 snorkeling                               0.00
                 surfing                                  0.00
                 swimming                                 0.00
                 walk/stand/play & others                 0.00
BRAZIL           bathing/floating                         0.00
                 diving                                   0.00
                 fishing and other types                  0.00
                 other watersports                       27.00
                 surfing                                 19.67
                 swimming                                21.70
                 walk/stand/play & others                 0.00
FIJI             diving                                  23.50
                 fishing and other types                 26.00
                 snorkeling                               0.00
                 surfing                                  0.00
                 swimming                                47.00
ITALY            fishing and other types                 28.00
...                                                        ...
PAPUA NEW GUINEA walk/stand/play & others                 0.00
PHILIPPINES      bathing/floating                         0.00
                 fishing and other types                 39.00
                 surfing                                 58.00
                 swimming                                20.00
REUNION          fishing and other types                  0.00
                 other watersports                       35.00
                 surfing                                 22.33
                 swimming                                52.00
SOUTH AFRICA     bathing/floating                        19.50
                 diving                                  52.00
                 fishing and other types                 27.00
                 other watersports                       18.80
                 snorkeling                               0.00
                 surfing                                 23.58
                 swimming                                21.07
                 walk/stand/play & others                21.75
                 war/battle                               0.00

# This analysis shows the type of person that can potentialy die attacked by a shark.

### Our target for our "Shark attack deaths prevention" marketing campaign would be:

### Campaign 1:
#### Men interested in watersports specialy surfing, fishing, swimming and diving, between 25 and 30 years old. 

### Campaign 2:
#### Men & women interested in seaside activities such as walking, running, playing and sea sightseeing, between 20 and 35 years old.

### The marketing campaign would be released by country according to local languages and in collaboration with the local governments and authorities in order to make the campaign as successfull as possible.